// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: mirage.proto

package proto

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// ========== GatewayUplink Client ==========

// GatewayUplinkClient 上行客户端接口
type GatewayUplinkClient interface {
	SyncHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	ReportTraffic(ctx context.Context, in *TrafficRequest, opts ...grpc.CallOption) (*TrafficResponse, error)
	ReportThreat(ctx context.Context, in *ThreatRequest, opts ...grpc.CallOption) (*ThreatResponse, error)
}

type gatewayUplinkClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayUplinkClient(cc grpc.ClientConnInterface) GatewayUplinkClient {
	return &gatewayUplinkClient{cc}
}

func (c *gatewayUplinkClient) SyncHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, "/mirage.GatewayUplink/SyncHeartbeat", in, out, opts...)
	return out, err
}

func (c *gatewayUplinkClient) ReportTraffic(ctx context.Context, in *TrafficRequest, opts ...grpc.CallOption) (*TrafficResponse, error) {
	out := new(TrafficResponse)
	err := c.cc.Invoke(ctx, "/mirage.GatewayUplink/ReportTraffic", in, out, opts...)
	return out, err
}

func (c *gatewayUplinkClient) ReportThreat(ctx context.Context, in *ThreatRequest, opts ...grpc.CallOption) (*ThreatResponse, error) {
	out := new(ThreatResponse)
	err := c.cc.Invoke(ctx, "/mirage.GatewayUplink/ReportThreat", in, out, opts...)
	return out, err
}

// ========== GatewayUplink Server ==========

// GatewayUplinkServer 上行服务端接口
type GatewayUplinkServer interface {
	SyncHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	ReportTraffic(context.Context, *TrafficRequest) (*TrafficResponse, error)
	ReportThreat(context.Context, *ThreatRequest) (*ThreatResponse, error)
	mustEmbedUnimplementedGatewayUplinkServer()
}

// UnimplementedGatewayUplinkServer 未实现的上行服务端
type UnimplementedGatewayUplinkServer struct{}

func (UnimplementedGatewayUplinkServer) SyncHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncHeartbeat not implemented")
}
func (UnimplementedGatewayUplinkServer) ReportTraffic(context.Context, *TrafficRequest) (*TrafficResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportTraffic not implemented")
}
func (UnimplementedGatewayUplinkServer) ReportThreat(context.Context, *ThreatRequest) (*ThreatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportThreat not implemented")
}
func (UnimplementedGatewayUplinkServer) mustEmbedUnimplementedGatewayUplinkServer() {}

// UnsafeGatewayUplinkServer 不安全的上行服务端
type UnsafeGatewayUplinkServer interface {
	mustEmbedUnimplementedGatewayUplinkServer()
}

// RegisterGatewayUplinkServer 注册上行服务
func RegisterGatewayUplinkServer(s grpc.ServiceRegistrar, srv GatewayUplinkServer) {
	s.RegisterService(&GatewayUplink_ServiceDesc, srv)
}

// GatewayUplink_ServiceDesc 上行服务描述
var GatewayUplink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mirage.GatewayUplink",
	HandlerType: (*GatewayUplinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "SyncHeartbeat", Handler: _GatewayUplink_SyncHeartbeat_Handler},
		{MethodName: "ReportTraffic", Handler: _GatewayUplink_ReportTraffic_Handler},
		{MethodName: "ReportThreat", Handler: _GatewayUplink_ReportThreat_Handler},
	},
	Streams: []grpc.StreamDesc{},
}

func _GatewayUplink_SyncHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayUplinkServer).SyncHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/mirage.GatewayUplink/SyncHeartbeat"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayUplinkServer).SyncHeartbeat(ctx, req.(*HeartbeatRequest))
	})
}

func _GatewayUplink_ReportTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrafficRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayUplinkServer).ReportTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/mirage.GatewayUplink/ReportTraffic"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayUplinkServer).ReportTraffic(ctx, req.(*TrafficRequest))
	})
}

func _GatewayUplink_ReportThreat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThreatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayUplinkServer).ReportThreat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/mirage.GatewayUplink/ReportThreat"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayUplinkServer).ReportThreat(ctx, req.(*ThreatRequest))
	})
}

// ========== GatewayDownlink Client ==========

// GatewayDownlinkClient 下行客户端接口
type GatewayDownlinkClient interface {
	PushBlacklist(ctx context.Context, in *BlacklistPush, opts ...grpc.CallOption) (*PushResponse, error)
	PushStrategy(ctx context.Context, in *StrategyPush, opts ...grpc.CallOption) (*PushResponse, error)
	PushQuota(ctx context.Context, in *QuotaPush, opts ...grpc.CallOption) (*PushResponse, error)
	PushReincarnation(ctx context.Context, in *ReincarnationPush, opts ...grpc.CallOption) (*PushResponse, error)
}

type gatewayDownlinkClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayDownlinkClient(cc grpc.ClientConnInterface) GatewayDownlinkClient {
	return &gatewayDownlinkClient{cc}
}

func (c *gatewayDownlinkClient) PushBlacklist(ctx context.Context, in *BlacklistPush, opts ...grpc.CallOption) (*PushResponse, error) {
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, "/mirage.GatewayDownlink/PushBlacklist", in, out, opts...)
	return out, err
}

func (c *gatewayDownlinkClient) PushStrategy(ctx context.Context, in *StrategyPush, opts ...grpc.CallOption) (*PushResponse, error) {
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, "/mirage.GatewayDownlink/PushStrategy", in, out, opts...)
	return out, err
}

func (c *gatewayDownlinkClient) PushQuota(ctx context.Context, in *QuotaPush, opts ...grpc.CallOption) (*PushResponse, error) {
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, "/mirage.GatewayDownlink/PushQuota", in, out, opts...)
	return out, err
}

func (c *gatewayDownlinkClient) PushReincarnation(ctx context.Context, in *ReincarnationPush, opts ...grpc.CallOption) (*PushResponse, error) {
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, "/mirage.GatewayDownlink/PushReincarnation", in, out, opts...)
	return out, err
}

// ========== GatewayDownlink Server ==========

// GatewayDownlinkServer 下行服务端接口
type GatewayDownlinkServer interface {
	PushBlacklist(context.Context, *BlacklistPush) (*PushResponse, error)
	PushStrategy(context.Context, *StrategyPush) (*PushResponse, error)
	PushQuota(context.Context, *QuotaPush) (*PushResponse, error)
	PushReincarnation(context.Context, *ReincarnationPush) (*PushResponse, error)
	mustEmbedUnimplementedGatewayDownlinkServer()
}

// UnimplementedGatewayDownlinkServer 未实现的下行服务端
type UnimplementedGatewayDownlinkServer struct{}

func (UnimplementedGatewayDownlinkServer) PushBlacklist(context.Context, *BlacklistPush) (*PushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushBlacklist not implemented")
}
func (UnimplementedGatewayDownlinkServer) PushStrategy(context.Context, *StrategyPush) (*PushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushStrategy not implemented")
}
func (UnimplementedGatewayDownlinkServer) PushQuota(context.Context, *QuotaPush) (*PushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushQuota not implemented")
}
func (UnimplementedGatewayDownlinkServer) PushReincarnation(context.Context, *ReincarnationPush) (*PushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushReincarnation not implemented")
}
func (UnimplementedGatewayDownlinkServer) mustEmbedUnimplementedGatewayDownlinkServer() {}

// UnsafeGatewayDownlinkServer 不安全的下行服务端
type UnsafeGatewayDownlinkServer interface {
	mustEmbedUnimplementedGatewayDownlinkServer()
}

// RegisterGatewayDownlinkServer 注册下行服务
func RegisterGatewayDownlinkServer(s grpc.ServiceRegistrar, srv GatewayDownlinkServer) {
	s.RegisterService(&GatewayDownlink_ServiceDesc, srv)
}

// GatewayDownlink_ServiceDesc 下行服务描述
var GatewayDownlink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mirage.GatewayDownlink",
	HandlerType: (*GatewayDownlinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "PushBlacklist", Handler: _GatewayDownlink_PushBlacklist_Handler},
		{MethodName: "PushStrategy", Handler: _GatewayDownlink_PushStrategy_Handler},
		{MethodName: "PushQuota", Handler: _GatewayDownlink_PushQuota_Handler},
		{MethodName: "PushReincarnation", Handler: _GatewayDownlink_PushReincarnation_Handler},
	},
	Streams: []grpc.StreamDesc{},
}

func _GatewayDownlink_PushBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlacklistPush)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDownlinkServer).PushBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/mirage.GatewayDownlink/PushBlacklist"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDownlinkServer).PushBlacklist(ctx, req.(*BlacklistPush))
	})
}

func _GatewayDownlink_PushStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyPush)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDownlinkServer).PushStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/mirage.GatewayDownlink/PushStrategy"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDownlinkServer).PushStrategy(ctx, req.(*StrategyPush))
	})
}

func _GatewayDownlink_PushQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuotaPush)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDownlinkServer).PushQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/mirage.GatewayDownlink/PushQuota"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDownlinkServer).PushQuota(ctx, req.(*QuotaPush))
	})
}

func _GatewayDownlink_PushReincarnation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReincarnationPush)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDownlinkServer).PushReincarnation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/mirage.GatewayDownlink/PushReincarnation"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDownlinkServer).PushReincarnation(ctx, req.(*ReincarnationPush))
	})
}
