// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mirage.proto

package proto

// GatewayStatus 枚举
type GatewayStatus int32

const (
	GatewayStatus_ONLINE    GatewayStatus = 0
	GatewayStatus_DEGRADED  GatewayStatus = 1
	GatewayStatus_EMERGENCY GatewayStatus = 2
)

// ThreatType 枚举
type ThreatType int32

const (
	ThreatType_THREAT_UNKNOWN ThreatType = 0
	ThreatType_ACTIVE_PROBING ThreatType = 1
	ThreatType_REPLAY_ATTACK  ThreatType = 2
	ThreatType_TIMING_ATTACK  ThreatType = 3
	ThreatType_DPI_DETECTION  ThreatType = 4
	ThreatType_JA4_SCAN       ThreatType = 5
	ThreatType_SNI_PROBE      ThreatType = 6
)

// BlacklistSourceType 枚举
type BlacklistSourceType int32

const (
	BlacklistSourceType_BL_LOCAL  BlacklistSourceType = 0
	BlacklistSourceType_BL_GLOBAL BlacklistSourceType = 1
)

// HeartbeatRequest 心跳请求
type HeartbeatRequest struct {
	GatewayId         string        `json:"gateway_id,omitempty"`
	Timestamp         int64         `json:"timestamp,omitempty"`
	Status            GatewayStatus `json:"status,omitempty"`
	EbpfLoaded        bool          `json:"ebpf_loaded,omitempty"`
	ThreatLevel       int32         `json:"threat_level,omitempty"`
	ActiveConnections int64         `json:"active_connections,omitempty"`
	MemoryUsageMb     int32         `json:"memory_usage_mb,omitempty"`
}

// HeartbeatResponse 心跳响应
type HeartbeatResponse struct {
	Ack        bool  `json:"ack,omitempty"`
	ServerTime int64 `json:"server_time,omitempty"`
}

// TrafficRequest 流量上报请求
type TrafficRequest struct {
	GatewayId     string `json:"gateway_id,omitempty"`
	Timestamp     int64  `json:"timestamp,omitempty"`
	BusinessBytes uint64 `json:"business_bytes,omitempty"`
	DefenseBytes  uint64 `json:"defense_bytes,omitempty"`
	PeriodSeconds int32  `json:"period_seconds,omitempty"`
}

// TrafficResponse 流量上报响应
type TrafficResponse struct {
	Ack bool `json:"ack,omitempty"`
}

// ThreatEvent 威胁事件
type ThreatEvent struct {
	Timestamp   int64      `json:"timestamp,omitempty"`
	ThreatType  ThreatType `json:"threat_type,omitempty"`
	SourceIp    string     `json:"source_ip,omitempty"`
	SourcePort  uint32     `json:"source_port,omitempty"`
	Severity    int32      `json:"severity,omitempty"`
	PacketCount uint32     `json:"packet_count,omitempty"`
}

// ThreatRequest 威胁上报请求
type ThreatRequest struct {
	GatewayId string         `json:"gateway_id,omitempty"`
	Events    []*ThreatEvent `json:"events,omitempty"`
}

// ThreatResponse 威胁上报响应
type ThreatResponse struct {
	Ack bool `json:"ack,omitempty"`
}

// BlacklistEntryProto 黑名单条目
type BlacklistEntryProto struct {
	Cidr     string              `json:"cidr,omitempty"`
	ExpireAt int64               `json:"expire_at,omitempty"`
	Source   BlacklistSourceType `json:"source,omitempty"`
}

// BlacklistPush 黑名单下发
type BlacklistPush struct {
	Entries []*BlacklistEntryProto `json:"entries,omitempty"`
}

// StrategyPush 策略下发
type StrategyPush struct {
	DefenseLevel   int32  `json:"defense_level,omitempty"`
	JitterMeanUs   uint32 `json:"jitter_mean_us,omitempty"`
	JitterStddevUs uint32 `json:"jitter_stddev_us,omitempty"`
	NoiseIntensity uint32 `json:"noise_intensity,omitempty"`
	PaddingRate    uint32 `json:"padding_rate,omitempty"`
	TemplateId     uint32 `json:"template_id,omitempty"`
}

// QuotaPush 配额下发
type QuotaPush struct {
	RemainingBytes uint64 `json:"remaining_bytes,omitempty"`
}

// ReincarnationPush 转生指令
type ReincarnationPush struct {
	NewDomain       string `json:"new_domain,omitempty"`
	NewIp           string `json:"new_ip,omitempty"`
	Reason          string `json:"reason,omitempty"`
	DeadlineSeconds int32  `json:"deadline_seconds,omitempty"`
}

// PushResponse 下行响应
type PushResponse struct {
	Success bool   `json:"success,omitempty"`
	Message string `json:"message,omitempty"`
}
