// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// ========== GatewayUplink ==========

type GatewayUplinkClient interface {
	SyncHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	ReportTraffic(ctx context.Context, in *TrafficRequest, opts ...grpc.CallOption) (*TrafficResponse, error)
	ReportThreat(ctx context.Context, in *ThreatRequest, opts ...grpc.CallOption) (*ThreatResponse, error)
}

type gatewayUplinkClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayUplinkClient(cc grpc.ClientConnInterface) GatewayUplinkClient {
	return &gatewayUplinkClient{cc}
}

func (c *gatewayUplinkClient) SyncHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, "/mirage.GatewayUplink/SyncHeartbeat", in, out, opts...)
	return out, err
}

func (c *gatewayUplinkClient) ReportTraffic(ctx context.Context, in *TrafficRequest, opts ...grpc.CallOption) (*TrafficResponse, error) {
	out := new(TrafficResponse)
	err := c.cc.Invoke(ctx, "/mirage.GatewayUplink/ReportTraffic", in, out, opts...)
	return out, err
}

func (c *gatewayUplinkClient) ReportThreat(ctx context.Context, in *ThreatRequest, opts ...grpc.CallOption) (*ThreatResponse, error) {
	out := new(ThreatResponse)
	err := c.cc.Invoke(ctx, "/mirage.GatewayUplink/ReportThreat", in, out, opts...)
	return out, err
}

type GatewayUplinkServer interface {
	SyncHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	ReportTraffic(context.Context, *TrafficRequest) (*TrafficResponse, error)
	ReportThreat(context.Context, *ThreatRequest) (*ThreatResponse, error)
	mustEmbedUnimplementedGatewayUplinkServer()
}

type UnimplementedGatewayUplinkServer struct{}

func (UnimplementedGatewayUplinkServer) SyncHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncHeartbeat not implemented")
}
func (UnimplementedGatewayUplinkServer) ReportTraffic(context.Context, *TrafficRequest) (*TrafficResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportTraffic not implemented")
}
func (UnimplementedGatewayUplinkServer) ReportThreat(context.Context, *ThreatRequest) (*ThreatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportThreat not implemented")
}
func (UnimplementedGatewayUplinkServer) mustEmbedUnimplementedGatewayUplinkServer() {}

type UnsafeGatewayUplinkServer interface {
	mustEmbedUnimplementedGatewayUplinkServer()
}

func RegisterGatewayUplinkServer(s grpc.ServiceRegistrar, srv GatewayUplinkServer) {
	s.RegisterService(&GatewayUplink_ServiceDesc, srv)
}

func _GatewayUplink_SyncHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayUplinkServer).SyncHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/mirage.GatewayUplink/SyncHeartbeat"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayUplinkServer).SyncHeartbeat(ctx, req.(*HeartbeatRequest))
	})
}

func _GatewayUplink_ReportTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrafficRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayUplinkServer).ReportTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/mirage.GatewayUplink/ReportTraffic"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayUplinkServer).ReportTraffic(ctx, req.(*TrafficRequest))
	})
}

func _GatewayUplink_ReportThreat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThreatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayUplinkServer).ReportThreat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/mirage.GatewayUplink/ReportThreat"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayUplinkServer).ReportThreat(ctx, req.(*ThreatRequest))
	})
}

var GatewayUplink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mirage.GatewayUplink",
	HandlerType: (*GatewayUplinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "SyncHeartbeat", Handler: _GatewayUplink_SyncHeartbeat_Handler},
		{MethodName: "ReportTraffic", Handler: _GatewayUplink_ReportTraffic_Handler},
		{MethodName: "ReportThreat", Handler: _GatewayUplink_ReportThreat_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mirage.proto",
}

// ========== GatewayDownlink ==========

type GatewayDownlinkClient interface {
	PushBlacklist(ctx context.Context, in *BlacklistPush, opts ...grpc.CallOption) (*PushResponse, error)
	PushStrategy(ctx context.Context, in *StrategyPush, opts ...grpc.CallOption) (*PushResponse, error)
	PushQuota(ctx context.Context, in *QuotaPush, opts ...grpc.CallOption) (*PushResponse, error)
	PushReincarnation(ctx context.Context, in *ReincarnationPush, opts ...grpc.CallOption) (*PushResponse, error)
}

type gatewayDownlinkClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayDownlinkClient(cc grpc.ClientConnInterface) GatewayDownlinkClient {
	return &gatewayDownlinkClient{cc}
}

func (c *gatewayDownlinkClient) PushBlacklist(ctx context.Context, in *BlacklistPush, opts ...grpc.CallOption) (*PushResponse, error) {
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, "/mirage.GatewayDownlink/PushBlacklist", in, out, opts...)
	return out, err
}

func (c *gatewayDownlinkClient) PushStrategy(ctx context.Context, in *StrategyPush, opts ...grpc.CallOption) (*PushResponse, error) {
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, "/mirage.GatewayDownlink/PushStrategy", in, out, opts...)
	return out, err
}

func (c *gatewayDownlinkClient) PushQuota(ctx context.Context, in *QuotaPush, opts ...grpc.CallOption) (*PushResponse, error) {
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, "/mirage.GatewayDownlink/PushQuota", in, out, opts...)
	return out, err
}

func (c *gatewayDownlinkClient) PushReincarnation(ctx context.Context, in *ReincarnationPush, opts ...grpc.CallOption) (*PushResponse, error) {
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, "/mirage.GatewayDownlink/PushReincarnation", in, out, opts...)
	return out, err
}

type GatewayDownlinkServer interface {
	PushBlacklist(context.Context, *BlacklistPush) (*PushResponse, error)
	PushStrategy(context.Context, *StrategyPush) (*PushResponse, error)
	PushQuota(context.Context, *QuotaPush) (*PushResponse, error)
	PushReincarnation(context.Context, *ReincarnationPush) (*PushResponse, error)
	mustEmbedUnimplementedGatewayDownlinkServer()
}

type UnimplementedGatewayDownlinkServer struct{}

func (UnimplementedGatewayDownlinkServer) PushBlacklist(context.Context, *BlacklistPush) (*PushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushBlacklist not implemented")
}
func (UnimplementedGatewayDownlinkServer) PushStrategy(context.Context, *StrategyPush) (*PushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushStrategy not implemented")
}
func (UnimplementedGatewayDownlinkServer) PushQuota(context.Context, *QuotaPush) (*PushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushQuota not implemented")
}
func (UnimplementedGatewayDownlinkServer) PushReincarnation(context.Context, *ReincarnationPush) (*PushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushReincarnation not implemented")
}
func (UnimplementedGatewayDownlinkServer) mustEmbedUnimplementedGatewayDownlinkServer() {}

type UnsafeGatewayDownlinkServer interface {
	mustEmbedUnimplementedGatewayDownlinkServer()
}

func RegisterGatewayDownlinkServer(s grpc.ServiceRegistrar, srv GatewayDownlinkServer) {
	s.RegisterService(&GatewayDownlink_ServiceDesc, srv)
}

var GatewayDownlink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mirage.GatewayDownlink",
	HandlerType: (*GatewayDownlinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "PushBlacklist", Handler: nil},
		{MethodName: "PushStrategy", Handler: nil},
		{MethodName: "PushQuota", Handler: nil},
		{MethodName: "PushReincarnation", Handler: nil},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mirage.proto",
}
