// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.0
// source: proto/mirage.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const _ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
const _ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)

type GatewayStatus int32

const (
	GatewayStatus_ONLINE    GatewayStatus = 0
	GatewayStatus_DEGRADED  GatewayStatus = 1
	GatewayStatus_EMERGENCY GatewayStatus = 2
)

var GatewayStatus_name = map[int32]string{0: "ONLINE", 1: "DEGRADED", 2: "EMERGENCY"}
var GatewayStatus_value = map[string]int32{"ONLINE": 0, "DEGRADED": 1, "EMERGENCY": 2}

func (x GatewayStatus) Enum() *GatewayStatus { p := new(GatewayStatus); *p = x; return p }
func (x GatewayStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}
func (GatewayStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_mirage_proto_enumTypes[0].Descriptor()
}
func (GatewayStatus) Type() protoreflect.EnumType       { return &file_mirage_proto_enumTypes[0] }
func (x GatewayStatus) Number() protoreflect.EnumNumber { return protoreflect.EnumNumber(x) }
func (GatewayStatus) EnumDescriptor() ([]byte, []int) {
	return file_mirage_proto_rawDescGZIP(), []int{0}
}

type ThreatType int32

const (
	ThreatType_THREAT_UNKNOWN ThreatType = 0
	ThreatType_ACTIVE_PROBING ThreatType = 1
	ThreatType_REPLAY_ATTACK  ThreatType = 2
	ThreatType_TIMING_ATTACK  ThreatType = 3
	ThreatType_DPI_DETECTION  ThreatType = 4
	ThreatType_JA4_SCAN       ThreatType = 5
	ThreatType_SNI_PROBE      ThreatType = 6
)

var ThreatType_name = map[int32]string{0: "THREAT_UNKNOWN", 1: "ACTIVE_PROBING", 2: "REPLAY_ATTACK", 3: "TIMING_ATTACK", 4: "DPI_DETECTION", 5: "JA4_SCAN", 6: "SNI_PROBE"}
var ThreatType_value = map[string]int32{"THREAT_UNKNOWN": 0, "ACTIVE_PROBING": 1, "REPLAY_ATTACK": 2, "TIMING_ATTACK": 3, "DPI_DETECTION": 4, "JA4_SCAN": 5, "SNI_PROBE": 6}

func (x ThreatType) Enum() *ThreatType { p := new(ThreatType); *p = x; return p }
func (x ThreatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}
func (ThreatType) Descriptor() protoreflect.EnumDescriptor {
	return file_mirage_proto_enumTypes[1].Descriptor()
}
func (ThreatType) Type() protoreflect.EnumType       { return &file_mirage_proto_enumTypes[1] }
func (x ThreatType) Number() protoreflect.EnumNumber { return protoreflect.EnumNumber(x) }
func (ThreatType) EnumDescriptor() ([]byte, []int)   { return file_mirage_proto_rawDescGZIP(), []int{1} }

type BlacklistSourceType int32

const (
	BlacklistSourceType_BL_LOCAL  BlacklistSourceType = 0
	BlacklistSourceType_BL_GLOBAL BlacklistSourceType = 1
)

var BlacklistSourceType_name = map[int32]string{0: "BL_LOCAL", 1: "BL_GLOBAL"}
var BlacklistSourceType_value = map[string]int32{"BL_LOCAL": 0, "BL_GLOBAL": 1}

func (x BlacklistSourceType) Enum() *BlacklistSourceType {
	p := new(BlacklistSourceType)
	*p = x
	return p
}
func (x BlacklistSourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}
func (BlacklistSourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_mirage_proto_enumTypes[2].Descriptor()
}
func (BlacklistSourceType) Type() protoreflect.EnumType       { return &file_mirage_proto_enumTypes[2] }
func (x BlacklistSourceType) Number() protoreflect.EnumNumber { return protoreflect.EnumNumber(x) }
func (BlacklistSourceType) EnumDescriptor() ([]byte, []int) {
	return file_mirage_proto_rawDescGZIP(), []int{2}
}

// ========== Messages ==========

type HeartbeatRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GatewayId         string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Timestamp         int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status            GatewayStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=mirage.GatewayStatus" json:"status,omitempty"`
	EbpfLoaded        bool                   `protobuf:"varint,4,opt,name=ebpf_loaded,json=ebpfLoaded,proto3" json:"ebpf_loaded,omitempty"`
	ThreatLevel       int32                  `protobuf:"varint,5,opt,name=threat_level,json=threatLevel,proto3" json:"threat_level,omitempty"`
	ActiveConnections int64                  `protobuf:"varint,6,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	MemoryUsageMb     int32                  `protobuf:"varint,7,opt,name=memory_usage_mb,json=memoryUsageMb,proto3" json:"memory_usage_mb,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset()         { *x = HeartbeatRequest{} }
func (x *HeartbeatRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *HeartbeatRequest) ProtoMessage()  {}
func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	return file_mirage_proto_msgTypes[0].MessageOf(x)
}
func (x *HeartbeatRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}
func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}
func (x *HeartbeatRequest) GetStatus() GatewayStatus {
	if x != nil {
		return x.Status
	}
	return GatewayStatus_ONLINE
}
func (x *HeartbeatRequest) GetEbpfLoaded() bool {
	if x != nil {
		return x.EbpfLoaded
	}
	return false
}
func (x *HeartbeatRequest) GetThreatLevel() int32 {
	if x != nil {
		return x.ThreatLevel
	}
	return 0
}
func (x *HeartbeatRequest) GetActiveConnections() int64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}
func (x *HeartbeatRequest) GetMemoryUsageMb() int32 {
	if x != nil {
		return x.MemoryUsageMb
	}
	return 0
}

type HeartbeatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ack            bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	ServerTime     int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	RemainingQuota float64                `protobuf:"fixed64,3,opt,name=remaining_quota,json=remainingQuota,proto3" json:"remaining_quota,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset()         { *x = HeartbeatResponse{} }
func (x *HeartbeatResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *HeartbeatResponse) ProtoMessage()  {}
func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	return file_mirage_proto_msgTypes[1].MessageOf(x)
}
func (x *HeartbeatResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}
func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}
func (x *HeartbeatResponse) GetRemainingQuota() float64 {
	if x != nil {
		return x.RemainingQuota
	}
	return 0
}

type TrafficRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GatewayId     string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BusinessBytes uint64                 `protobuf:"varint,3,opt,name=business_bytes,json=businessBytes,proto3" json:"business_bytes,omitempty"`
	DefenseBytes  uint64                 `protobuf:"varint,4,opt,name=defense_bytes,json=defenseBytes,proto3" json:"defense_bytes,omitempty"`
	PeriodSeconds int32                  `protobuf:"varint,5,opt,name=period_seconds,json=periodSeconds,proto3" json:"period_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficRequest) Reset()         { *x = TrafficRequest{} }
func (x *TrafficRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *TrafficRequest) ProtoMessage()  {}
func (x *TrafficRequest) ProtoReflect() protoreflect.Message {
	return file_mirage_proto_msgTypes[2].MessageOf(x)
}
func (x *TrafficRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}
func (x *TrafficRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}
func (x *TrafficRequest) GetBusinessBytes() uint64 {
	if x != nil {
		return x.BusinessBytes
	}
	return 0
}
func (x *TrafficRequest) GetDefenseBytes() uint64 {
	if x != nil {
		return x.DefenseBytes
	}
	return 0
}
func (x *TrafficRequest) GetPeriodSeconds() int32 {
	if x != nil {
		return x.PeriodSeconds
	}
	return 0
}

type TrafficResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficResponse) Reset()         { *x = TrafficResponse{} }
func (x *TrafficResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *TrafficResponse) ProtoMessage()  {}
func (x *TrafficResponse) ProtoReflect() protoreflect.Message {
	return file_mirage_proto_msgTypes[3].MessageOf(x)
}
func (x *TrafficResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

type ThreatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ThreatType    ThreatType             `protobuf:"varint,2,opt,name=threat_type,json=threatType,proto3,enum=mirage.ThreatType" json:"threat_type,omitempty"`
	SourceIp      string                 `protobuf:"bytes,3,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	SourcePort    uint32                 `protobuf:"varint,4,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	Severity      int32                  `protobuf:"varint,5,opt,name=severity,proto3" json:"severity,omitempty"`
	PacketCount   uint32                 `protobuf:"varint,6,opt,name=packet_count,json=packetCount,proto3" json:"packet_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatEvent) Reset()         { *x = ThreatEvent{} }
func (x *ThreatEvent) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *ThreatEvent) ProtoMessage()  {}
func (x *ThreatEvent) ProtoReflect() protoreflect.Message {
	return file_mirage_proto_msgTypes[4].MessageOf(x)
}
func (x *ThreatEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}
func (x *ThreatEvent) GetThreatType() ThreatType {
	if x != nil {
		return x.ThreatType
	}
	return ThreatType_THREAT_UNKNOWN
}
func (x *ThreatEvent) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}
func (x *ThreatEvent) GetSourcePort() uint32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}
func (x *ThreatEvent) GetSeverity() int32 {
	if x != nil {
		return x.Severity
	}
	return 0
}
func (x *ThreatEvent) GetPacketCount() uint32 {
	if x != nil {
		return x.PacketCount
	}
	return 0
}

type ThreatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GatewayId     string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Events        []*ThreatEvent         `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatRequest) Reset()         { *x = ThreatRequest{} }
func (x *ThreatRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *ThreatRequest) ProtoMessage()  {}
func (x *ThreatRequest) ProtoReflect() protoreflect.Message {
	return file_mirage_proto_msgTypes[5].MessageOf(x)
}
func (x *ThreatRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}
func (x *ThreatRequest) GetEvents() []*ThreatEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ThreatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatResponse) Reset()         { *x = ThreatResponse{} }
func (x *ThreatResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *ThreatResponse) ProtoMessage()  {}
func (x *ThreatResponse) ProtoReflect() protoreflect.Message {
	return file_mirage_proto_msgTypes[6].MessageOf(x)
}
func (x *ThreatResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

type BlacklistEntryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	ExpireAt      int64                  `protobuf:"varint,2,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	Source        BlacklistSourceType    `protobuf:"varint,3,opt,name=source,proto3,enum=mirage.BlacklistSourceType" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlacklistEntryProto) Reset()         { *x = BlacklistEntryProto{} }
func (x *BlacklistEntryProto) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *BlacklistEntryProto) ProtoMessage()  {}
func (x *BlacklistEntryProto) ProtoReflect() protoreflect.Message {
	return file_mirage_proto_msgTypes[7].MessageOf(x)
}
func (x *BlacklistEntryProto) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}
func (x *BlacklistEntryProto) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}
func (x *BlacklistEntryProto) GetSource() BlacklistSourceType {
	if x != nil {
		return x.Source
	}
	return BlacklistSourceType_BL_LOCAL
}

type BlacklistPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*BlacklistEntryProto `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlacklistPush) Reset()         { *x = BlacklistPush{} }
func (x *BlacklistPush) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *BlacklistPush) ProtoMessage()  {}
func (x *BlacklistPush) ProtoReflect() protoreflect.Message {
	return file_mirage_proto_msgTypes[8].MessageOf(x)
}
func (x *BlacklistPush) GetEntries() []*BlacklistEntryProto {
	if x != nil {
		return x.Entries
	}
	return nil
}

type StrategyPush struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DefenseLevel   int32                  `protobuf:"varint,1,opt,name=defense_level,json=defenseLevel,proto3" json:"defense_level,omitempty"`
	JitterMeanUs   uint32                 `protobuf:"varint,2,opt,name=jitter_mean_us,json=jitterMeanUs,proto3" json:"jitter_mean_us,omitempty"`
	JitterStddevUs uint32                 `protobuf:"varint,3,opt,name=jitter_stddev_us,json=jitterStddevUs,proto3" json:"jitter_stddev_us,omitempty"`
	NoiseIntensity uint32                 `protobuf:"varint,4,opt,name=noise_intensity,json=noiseIntensity,proto3" json:"noise_intensity,omitempty"`
	PaddingRate    uint32                 `protobuf:"varint,5,opt,name=padding_rate,json=paddingRate,proto3" json:"padding_rate,omitempty"`
	TemplateId     uint32                 `protobuf:"varint,6,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StrategyPush) Reset()         { *x = StrategyPush{} }
func (x *StrategyPush) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *StrategyPush) ProtoMessage()  {}
func (x *StrategyPush) ProtoReflect() protoreflect.Message {
	return file_mirage_proto_msgTypes[9].MessageOf(x)
}
func (x *StrategyPush) GetDefenseLevel() int32 {
	if x != nil {
		return x.DefenseLevel
	}
	return 0
}
func (x *StrategyPush) GetJitterMeanUs() uint32 {
	if x != nil {
		return x.JitterMeanUs
	}
	return 0
}
func (x *StrategyPush) GetJitterStddevUs() uint32 {
	if x != nil {
		return x.JitterStddevUs
	}
	return 0
}
func (x *StrategyPush) GetNoiseIntensity() uint32 {
	if x != nil {
		return x.NoiseIntensity
	}
	return 0
}
func (x *StrategyPush) GetPaddingRate() uint32 {
	if x != nil {
		return x.PaddingRate
	}
	return 0
}
func (x *StrategyPush) GetTemplateId() uint32 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

type QuotaPush struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RemainingBytes uint64                 `protobuf:"varint,1,opt,name=remaining_bytes,json=remainingBytes,proto3" json:"remaining_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuotaPush) Reset()         { *x = QuotaPush{} }
func (x *QuotaPush) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *QuotaPush) ProtoMessage()  {}
func (x *QuotaPush) ProtoReflect() protoreflect.Message {
	return file_mirage_proto_msgTypes[10].MessageOf(x)
}
func (x *QuotaPush) GetRemainingBytes() uint64 {
	if x != nil {
		return x.RemainingBytes
	}
	return 0
}

type ReincarnationPush struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NewDomain       string                 `protobuf:"bytes,1,opt,name=new_domain,json=newDomain,proto3" json:"new_domain,omitempty"`
	NewIp           string                 `protobuf:"bytes,2,opt,name=new_ip,json=newIp,proto3" json:"new_ip,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	DeadlineSeconds int32                  `protobuf:"varint,4,opt,name=deadline_seconds,json=deadlineSeconds,proto3" json:"deadline_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReincarnationPush) Reset()         { *x = ReincarnationPush{} }
func (x *ReincarnationPush) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *ReincarnationPush) ProtoMessage()  {}
func (x *ReincarnationPush) ProtoReflect() protoreflect.Message {
	return file_mirage_proto_msgTypes[11].MessageOf(x)
}
func (x *ReincarnationPush) GetNewDomain() string {
	if x != nil {
		return x.NewDomain
	}
	return ""
}
func (x *ReincarnationPush) GetNewIp() string {
	if x != nil {
		return x.NewIp
	}
	return ""
}
func (x *ReincarnationPush) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}
func (x *ReincarnationPush) GetDeadlineSeconds() int32 {
	if x != nil {
		return x.DeadlineSeconds
	}
	return 0
}

type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset()         { *x = PushResponse{} }
func (x *PushResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *PushResponse) ProtoMessage()  {}
func (x *PushResponse) ProtoReflect() protoreflect.Message {
	return file_mirage_proto_msgTypes[12].MessageOf(x)
}
func (x *PushResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}
func (x *PushResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// File descriptor and registration
var file_mirage_proto_rawDesc = []byte{0x0a}
var file_mirage_proto_rawDescOnce sync.Once
var file_mirage_proto_rawDescData = file_mirage_proto_rawDesc

func file_mirage_proto_rawDescGZIP() []byte {
	file_mirage_proto_rawDescOnce.Do(func() {
		file_mirage_proto_rawDescData = protoimpl.X.CompressGZIP(file_mirage_proto_rawDescData)
	})
	return file_mirage_proto_rawDescData
}

var file_mirage_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_mirage_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_mirage_proto_goTypes = []any{
	(GatewayStatus)(0),          // 0
	(ThreatType)(0),             // 1
	(BlacklistSourceType)(0),    // 2
	(*HeartbeatRequest)(nil),    // 3
	(*HeartbeatResponse)(nil),   // 4
	(*TrafficRequest)(nil),      // 5
	(*TrafficResponse)(nil),     // 6
	(*ThreatEvent)(nil),         // 7
	(*ThreatRequest)(nil),       // 8
	(*ThreatResponse)(nil),      // 9
	(*BlacklistEntryProto)(nil), // 10
	(*BlacklistPush)(nil),       // 11
	(*StrategyPush)(nil),        // 12
	(*QuotaPush)(nil),           // 13
	(*ReincarnationPush)(nil),   // 14
	(*PushResponse)(nil),        // 15
}

func init() { file_mirage_proto_init() }

func file_mirage_proto_init() {
	if file_mirage_proto_goTypes != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mirage_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:      file_mirage_proto_goTypes,
		EnumInfos:    file_mirage_proto_enumTypes,
		MessageInfos: file_mirage_proto_msgTypes,
	}.Build()
	_ = out
	_ = unsafe.Pointer(nil)
}
