// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: api/proto/billing.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackageType int32

const (
	PackageType_PACKAGE_UNKNOWN PackageType = 0
	PackageType_PACKAGE_10GB    PackageType = 1 // 10GB 包
	PackageType_PACKAGE_50GB    PackageType = 2 // 50GB 包
	PackageType_PACKAGE_100GB   PackageType = 3 // 100GB 包
	PackageType_PACKAGE_500GB   PackageType = 4 // 500GB 包
	PackageType_PACKAGE_1TB     PackageType = 5 // 1TB 包
)

// Enum value maps for PackageType.
var (
	PackageType_name = map[int32]string{
		0: "PACKAGE_UNKNOWN",
		1: "PACKAGE_10GB",
		2: "PACKAGE_50GB",
		3: "PACKAGE_100GB",
		4: "PACKAGE_500GB",
		5: "PACKAGE_1TB",
	}
	PackageType_value = map[string]int32{
		"PACKAGE_UNKNOWN": 0,
		"PACKAGE_10GB":    1,
		"PACKAGE_50GB":    2,
		"PACKAGE_100GB":   3,
		"PACKAGE_500GB":   4,
		"PACKAGE_1TB":     5,
	}
)

func (x PackageType) Enum() *PackageType {
	p := new(PackageType)
	*p = x
	return p
}

func (x PackageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackageType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_billing_proto_enumTypes[0].Descriptor()
}

func (PackageType) Type() protoreflect.EnumType {
	return &file_api_proto_billing_proto_enumTypes[0]
}

func (x PackageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackageType.Descriptor instead.
func (PackageType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_billing_proto_rawDescGZIP(), []int{0}
}

type LogType int32

const (
	LogType_LOG_UNKNOWN      LogType = 0
	LogType_LOG_TRAFFIC      LogType = 1 // 流量消费
	LogType_LOG_DEPOSIT      LogType = 2 // 充值
	LogType_LOG_PURCHASE     LogType = 3 // 购买流量包
	LogType_LOG_REFUND       LogType = 4 // 退款
	LogType_LOG_SUBSCRIPTION LogType = 5 // 等级订阅
	LogType_LOG_FUSE         LogType = 6 // 配额熔断
	LogType_LOG_DOWNGRADE    LogType = 7 // 等级降级
)

// Enum value maps for LogType.
var (
	LogType_name = map[int32]string{
		0: "LOG_UNKNOWN",
		1: "LOG_TRAFFIC",
		2: "LOG_DEPOSIT",
		3: "LOG_PURCHASE",
		4: "LOG_REFUND",
		5: "LOG_SUBSCRIPTION",
		6: "LOG_FUSE",
		7: "LOG_DOWNGRADE",
	}
	LogType_value = map[string]int32{
		"LOG_UNKNOWN":      0,
		"LOG_TRAFFIC":      1,
		"LOG_DEPOSIT":      2,
		"LOG_PURCHASE":     3,
		"LOG_REFUND":       4,
		"LOG_SUBSCRIPTION": 5,
		"LOG_FUSE":         6,
		"LOG_DOWNGRADE":    7,
	}
)

func (x LogType) Enum() *LogType {
	p := new(LogType)
	*p = x
	return p
}

func (x LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_billing_proto_enumTypes[1].Descriptor()
}

func (LogType) Type() protoreflect.EnumType {
	return &file_api_proto_billing_proto_enumTypes[1]
}

func (x LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogType.Descriptor instead.
func (LogType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_billing_proto_rawDescGZIP(), []int{1}
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 用户 ID（匿名哈希）
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // 公钥（用于验证）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_api_proto_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_billing_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAccountRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`  // 账户 ID
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_api_proto_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_billing_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateAccountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateAccountResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateAccountResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type DepositRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`  // 账户 ID
	TxHash        string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`           // Monero 交易哈希
	AmountXmr     uint64                 `protobuf:"varint,3,opt,name=amount_xmr,json=amountXmr,proto3" json:"amount_xmr,omitempty"` // 充值金额（XMR，单位：皮摩尔）
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositRequest) Reset() {
	*x = DepositRequest{}
	mi := &file_api_proto_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRequest) ProtoMessage() {}

func (x *DepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRequest.ProtoReflect.Descriptor instead.
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_billing_proto_rawDescGZIP(), []int{2}
}

func (x *DepositRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DepositRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *DepositRequest) GetAmountXmr() uint64 {
	if x != nil {
		return x.AmountXmr
	}
	return 0
}

func (x *DepositRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DepositResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	BalanceUsd    uint64                 `protobuf:"varint,3,opt,name=balance_usd,json=balanceUsd,proto3" json:"balance_usd,omitempty"`        // 余额（美元，单位：美分）
	ExchangeRate  float32                `protobuf:"fixed32,4,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"` // 汇率（XMR/USD）
	ConfirmedAt   int64                  `protobuf:"varint,5,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`     // 确认时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositResponse) Reset() {
	*x = DepositResponse{}
	mi := &file_api_proto_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositResponse) ProtoMessage() {}

func (x *DepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositResponse.ProtoReflect.Descriptor instead.
func (*DepositResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_billing_proto_rawDescGZIP(), []int{3}
}

func (x *DepositResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DepositResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DepositResponse) GetBalanceUsd() uint64 {
	if x != nil {
		return x.BalanceUsd
	}
	return 0
}

func (x *DepositResponse) GetExchangeRate() float32 {
	if x != nil {
		return x.ExchangeRate
	}
	return 0
}

func (x *DepositResponse) GetConfirmedAt() int64 {
	if x != nil {
		return x.ConfirmedAt
	}
	return 0
}

type BalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // 账户 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceRequest) Reset() {
	*x = BalanceRequest{}
	mi := &file_api_proto_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRequest) ProtoMessage() {}

func (x *BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRequest.ProtoReflect.Descriptor instead.
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_billing_proto_rawDescGZIP(), []int{4}
}

func (x *BalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type BalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	BalanceUsd    uint64                 `protobuf:"varint,3,opt,name=balance_usd,json=balanceUsd,proto3" json:"balance_usd,omitempty"` // 余额（美分）
	Quota         *QuotaInfo             `protobuf:"bytes,4,opt,name=quota,proto3" json:"quota,omitempty"`                              // 配额信息
	Cells         []*CellAllocation      `protobuf:"bytes,5,rep,name=cells,proto3" json:"cells,omitempty"`                              // 蜂窝分配
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_api_proto_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_billing_proto_rawDescGZIP(), []int{5}
}

func (x *BalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BalanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BalanceResponse) GetBalanceUsd() uint64 {
	if x != nil {
		return x.BalanceUsd
	}
	return 0
}

func (x *BalanceResponse) GetQuota() *QuotaInfo {
	if x != nil {
		return x.Quota
	}
	return nil
}

func (x *BalanceResponse) GetCells() []*CellAllocation {
	if x != nil {
		return x.Cells
	}
	return nil
}

type QuotaInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalBytes     uint64                 `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`             // 总配额（字节）
	UsedBytes      uint64                 `protobuf:"varint,2,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`                // 已用流量
	RemainingBytes uint64                 `protobuf:"varint,3,opt,name=remaining_bytes,json=remainingBytes,proto3" json:"remaining_bytes,omitempty"` // 剩余流量
	ExpiresAt      int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`                // 过期时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuotaInfo) Reset() {
	*x = QuotaInfo{}
	mi := &file_api_proto_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaInfo) ProtoMessage() {}

func (x *QuotaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaInfo.ProtoReflect.Descriptor instead.
func (*QuotaInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_billing_proto_rawDescGZIP(), []int{6}
}

func (x *QuotaInfo) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *QuotaInfo) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *QuotaInfo) GetRemainingBytes() uint64 {
	if x != nil {
		return x.RemainingBytes
	}
	return 0
}

func (x *QuotaInfo) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type CellAllocation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CellId         string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`                           // 蜂窝 ID
	CellLevel      string                 `protobuf:"bytes,2,opt,name=cell_level,json=cellLevel,proto3" json:"cell_level,omitempty"`                  // 等级（standard/platinum/diamond）
	AllocatedBytes uint64                 `protobuf:"varint,3,opt,name=allocated_bytes,json=allocatedBytes,proto3" json:"allocated_bytes,omitempty"`  // 分配流量
	UsedBytes      uint64                 `protobuf:"varint,4,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`                 // 已用流量
	CostMultiplier float32                `protobuf:"fixed32,5,opt,name=cost_multiplier,json=costMultiplier,proto3" json:"cost_multiplier,omitempty"` // 成本倍率
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CellAllocation) Reset() {
	*x = CellAllocation{}
	mi := &file_api_proto_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellAllocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellAllocation) ProtoMessage() {}

func (x *CellAllocation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellAllocation.ProtoReflect.Descriptor instead.
func (*CellAllocation) Descriptor() ([]byte, []int) {
	return file_api_proto_billing_proto_rawDescGZIP(), []int{7}
}

func (x *CellAllocation) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *CellAllocation) GetCellLevel() string {
	if x != nil {
		return x.CellLevel
	}
	return ""
}

func (x *CellAllocation) GetAllocatedBytes() uint64 {
	if x != nil {
		return x.AllocatedBytes
	}
	return 0
}

func (x *CellAllocation) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *CellAllocation) GetCostMultiplier() float32 {
	if x != nil {
		return x.CostMultiplier
	}
	return 0
}

type PurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`                                           // 账户 ID
	PackageType   PackageType            `protobuf:"varint,2,opt,name=package_type,json=packageType,proto3,enum=mirage.billing.v1.PackageType" json:"package_type,omitempty"` // 流量包类型
	CellLevel     string                 `protobuf:"bytes,3,opt,name=cell_level,json=cellLevel,proto3" json:"cell_level,omitempty"`                                           // 蜂窝等级
	Quantity      uint32                 `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`                                                             // 购买数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseRequest) Reset() {
	*x = PurchaseRequest{}
	mi := &file_api_proto_billing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseRequest) ProtoMessage() {}

func (x *PurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_billing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseRequest.ProtoReflect.Descriptor instead.
func (*PurchaseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_billing_proto_rawDescGZIP(), []int{8}
}

func (x *PurchaseRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *PurchaseRequest) GetPackageType() PackageType {
	if x != nil {
		return x.PackageType
	}
	return PackageType_PACKAGE_UNKNOWN
}

func (x *PurchaseRequest) GetCellLevel() string {
	if x != nil {
		return x.CellLevel
	}
	return ""
}

func (x *PurchaseRequest) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type PurchaseResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CostUsd          uint64                 `protobuf:"varint,3,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`                            // 费用（美分）
	RemainingBalance uint64                 `protobuf:"varint,4,opt,name=remaining_balance,json=remainingBalance,proto3" json:"remaining_balance,omitempty"` // 剩余余额
	QuotaAdded       uint64                 `protobuf:"varint,5,opt,name=quota_added,json=quotaAdded,proto3" json:"quota_added,omitempty"`                   // 增加的配额（字节）
	ExpiresAt        int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`                      // 过期时间
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PurchaseResponse) Reset() {
	*x = PurchaseResponse{}
	mi := &file_api_proto_billing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseResponse) ProtoMessage() {}

func (x *PurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_billing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseResponse.ProtoReflect.Descriptor instead.
func (*PurchaseResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_billing_proto_rawDescGZIP(), []int{9}
}

func (x *PurchaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PurchaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PurchaseResponse) GetCostUsd() uint64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

func (x *PurchaseResponse) GetRemainingBalance() uint64 {
	if x != nil {
		return x.RemainingBalance
	}
	return 0
}

func (x *PurchaseResponse) GetQuotaAdded() uint64 {
	if x != nil {
		return x.QuotaAdded
	}
	return 0
}

func (x *PurchaseResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type BillingLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`  // 账户 ID
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 开始时间
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // 结束时间
	Limit         uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                          // 返回条数限制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillingLogsRequest) Reset() {
	*x = BillingLogsRequest{}
	mi := &file_api_proto_billing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillingLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingLogsRequest) ProtoMessage() {}

func (x *BillingLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_billing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingLogsRequest.ProtoReflect.Descriptor instead.
func (*BillingLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_billing_proto_rawDescGZIP(), []int{10}
}

func (x *BillingLogsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *BillingLogsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *BillingLogsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *BillingLogsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type BillingLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Logs          []*BillingLog          `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`                                // 流水记录
	TotalCount    uint32                 `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // 总记录数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillingLogsResponse) Reset() {
	*x = BillingLogsResponse{}
	mi := &file_api_proto_billing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillingLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingLogsResponse) ProtoMessage() {}

func (x *BillingLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_billing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingLogsResponse.ProtoReflect.Descriptor instead.
func (*BillingLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_billing_proto_rawDescGZIP(), []int{11}
}

func (x *BillingLogsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BillingLogsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BillingLogsResponse) GetLogs() []*BillingLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *BillingLogsResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type BillingLog struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	LogId               string                 `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`                                              // 流水 ID
	GatewayId           string                 `protobuf:"bytes,2,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`                                  // Gateway ID
	Timestamp           int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                  // 时间戳
	BaseTrafficBytes    uint64                 `protobuf:"varint,4,opt,name=base_traffic_bytes,json=baseTrafficBytes,proto3" json:"base_traffic_bytes,omitempty"`          // 业务流量
	DefenseTrafficBytes uint64                 `protobuf:"varint,5,opt,name=defense_traffic_bytes,json=defenseTrafficBytes,proto3" json:"defense_traffic_bytes,omitempty"` // 防御流量
	CostUsd             uint64                 `protobuf:"varint,6,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`                                       // 费用（美分）
	CellId              string                 `protobuf:"bytes,7,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`                                           // 蜂窝 ID
	CostMultiplier      float32                `protobuf:"fixed32,8,opt,name=cost_multiplier,json=costMultiplier,proto3" json:"cost_multiplier,omitempty"`                 // 成本倍率
	LogType             LogType                `protobuf:"varint,9,opt,name=log_type,json=logType,proto3,enum=mirage.billing.v1.LogType" json:"log_type,omitempty"`        // 流水类型
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BillingLog) Reset() {
	*x = BillingLog{}
	mi := &file_api_proto_billing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillingLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingLog) ProtoMessage() {}

func (x *BillingLog) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_billing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingLog.ProtoReflect.Descriptor instead.
func (*BillingLog) Descriptor() ([]byte, []int) {
	return file_api_proto_billing_proto_rawDescGZIP(), []int{12}
}

func (x *BillingLog) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *BillingLog) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *BillingLog) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BillingLog) GetBaseTrafficBytes() uint64 {
	if x != nil {
		return x.BaseTrafficBytes
	}
	return 0
}

func (x *BillingLog) GetDefenseTrafficBytes() uint64 {
	if x != nil {
		return x.DefenseTrafficBytes
	}
	return 0
}

func (x *BillingLog) GetCostUsd() uint64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

func (x *BillingLog) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *BillingLog) GetCostMultiplier() float32 {
	if x != nil {
		return x.CostMultiplier
	}
	return 0
}

func (x *BillingLog) GetLogType() LogType {
	if x != nil {
		return x.LogType
	}
	return LogType_LOG_UNKNOWN
}

type TierSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // 账户 ID
	PlanType      string                 `protobuf:"bytes,2,opt,name=plan_type,json=planType,proto3" json:"plan_type,omitempty"`    // 月费产品类型: plan_standard_monthly / plan_platinum_monthly / plan_diamond_monthly
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TierSubscriptionRequest) Reset() {
	*x = TierSubscriptionRequest{}
	mi := &file_api_proto_billing_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TierSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TierSubscriptionRequest) ProtoMessage() {}

func (x *TierSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_billing_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TierSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*TierSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_billing_proto_rawDescGZIP(), []int{13}
}

func (x *TierSubscriptionRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *TierSubscriptionRequest) GetPlanType() string {
	if x != nil {
		return x.PlanType
	}
	return ""
}

type TierSubscriptionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CostUsd          uint64                 `protobuf:"varint,3,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`                            // 费用（美分）
	RemainingBalance uint64                 `protobuf:"varint,4,opt,name=remaining_balance,json=remainingBalance,proto3" json:"remaining_balance,omitempty"` // 剩余余额（美分）
	NewCellLevel     int32                  `protobuf:"varint,5,opt,name=new_cell_level,json=newCellLevel,proto3" json:"new_cell_level,omitempty"`           // 新等级
	ExpiresAt        int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`                      // 订阅到期时间
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TierSubscriptionResponse) Reset() {
	*x = TierSubscriptionResponse{}
	mi := &file_api_proto_billing_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TierSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TierSubscriptionResponse) ProtoMessage() {}

func (x *TierSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_billing_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TierSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*TierSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_billing_proto_rawDescGZIP(), []int{14}
}

func (x *TierSubscriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TierSubscriptionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TierSubscriptionResponse) GetCostUsd() uint64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

func (x *TierSubscriptionResponse) GetRemainingBalance() uint64 {
	if x != nil {
		return x.RemainingBalance
	}
	return 0
}

func (x *TierSubscriptionResponse) GetNewCellLevel() int32 {
	if x != nil {
		return x.NewCellLevel
	}
	return 0
}

func (x *TierSubscriptionResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_api_proto_billing_proto protoreflect.FileDescriptor

const file_api_proto_billing_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/billing.proto\x12\x11mirage.billing.v1\"N\n" +
	"\x14CreateAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\"\x89\x01\n" +
	"\x15CreateAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"\x85\x01\n" +
	"\x0eDepositRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12\x1d\n" +
	"\n" +
	"amount_xmr\x18\x03 \x01(\x04R\tamountXmr\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xae\x01\n" +
	"\x0fDepositResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vbalance_usd\x18\x03 \x01(\x04R\n" +
	"balanceUsd\x12#\n" +
	"\rexchange_rate\x18\x04 \x01(\x02R\fexchangeRate\x12!\n" +
	"\fconfirmed_at\x18\x05 \x01(\x03R\vconfirmedAt\"/\n" +
	"\x0eBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\xd3\x01\n" +
	"\x0fBalanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vbalance_usd\x18\x03 \x01(\x04R\n" +
	"balanceUsd\x122\n" +
	"\x05quota\x18\x04 \x01(\v2\x1c.mirage.billing.v1.QuotaInfoR\x05quota\x127\n" +
	"\x05cells\x18\x05 \x03(\v2!.mirage.billing.v1.CellAllocationR\x05cells\"\x93\x01\n" +
	"\tQuotaInfo\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x02 \x01(\x04R\tusedBytes\x12'\n" +
	"\x0fremaining_bytes\x18\x03 \x01(\x04R\x0eremainingBytes\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"\xb9\x01\n" +
	"\x0eCellAllocation\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\x12\x1d\n" +
	"\n" +
	"cell_level\x18\x02 \x01(\tR\tcellLevel\x12'\n" +
	"\x0fallocated_bytes\x18\x03 \x01(\x04R\x0eallocatedBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x04 \x01(\x04R\tusedBytes\x12'\n" +
	"\x0fcost_multiplier\x18\x05 \x01(\x02R\x0ecostMultiplier\"\xae\x01\n" +
	"\x0fPurchaseRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12A\n" +
	"\fpackage_type\x18\x02 \x01(\x0e2\x1e.mirage.billing.v1.PackageTypeR\vpackageType\x12\x1d\n" +
	"\n" +
	"cell_level\x18\x03 \x01(\tR\tcellLevel\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\rR\bquantity\"\xce\x01\n" +
	"\x10PurchaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bcost_usd\x18\x03 \x01(\x04R\acostUsd\x12+\n" +
	"\x11remaining_balance\x18\x04 \x01(\x04R\x10remainingBalance\x12\x1f\n" +
	"\vquota_added\x18\x05 \x01(\x04R\n" +
	"quotaAdded\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\"\x83\x01\n" +
	"\x12BillingLogsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\"\x9d\x01\n" +
	"\x13BillingLogsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04logs\x18\x03 \x03(\v2\x1d.mirage.billing.v1.BillingLogR\x04logs\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\rR\n" +
	"totalCount\"\xd6\x02\n" +
	"\n" +
	"BillingLog\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\tR\x05logId\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x02 \x01(\tR\tgatewayId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12,\n" +
	"\x12base_traffic_bytes\x18\x04 \x01(\x04R\x10baseTrafficBytes\x122\n" +
	"\x15defense_traffic_bytes\x18\x05 \x01(\x04R\x13defenseTrafficBytes\x12\x19\n" +
	"\bcost_usd\x18\x06 \x01(\x04R\acostUsd\x12\x17\n" +
	"\acell_id\x18\a \x01(\tR\x06cellId\x12'\n" +
	"\x0fcost_multiplier\x18\b \x01(\x02R\x0ecostMultiplier\x125\n" +
	"\blog_type\x18\t \x01(\x0e2\x1a.mirage.billing.v1.LogTypeR\alogType\"U\n" +
	"\x17TierSubscriptionRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\tplan_type\x18\x02 \x01(\tR\bplanType\"\xdb\x01\n" +
	"\x18TierSubscriptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bcost_usd\x18\x03 \x01(\x04R\acostUsd\x12+\n" +
	"\x11remaining_balance\x18\x04 \x01(\x04R\x10remainingBalance\x12$\n" +
	"\x0enew_cell_level\x18\x05 \x01(\x05R\fnewCellLevel\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt*}\n" +
	"\vPackageType\x12\x13\n" +
	"\x0fPACKAGE_UNKNOWN\x10\x00\x12\x10\n" +
	"\fPACKAGE_10GB\x10\x01\x12\x10\n" +
	"\fPACKAGE_50GB\x10\x02\x12\x11\n" +
	"\rPACKAGE_100GB\x10\x03\x12\x11\n" +
	"\rPACKAGE_500GB\x10\x04\x12\x0f\n" +
	"\vPACKAGE_1TB\x10\x05*\x95\x01\n" +
	"\aLogType\x12\x0f\n" +
	"\vLOG_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vLOG_TRAFFIC\x10\x01\x12\x0f\n" +
	"\vLOG_DEPOSIT\x10\x02\x12\x10\n" +
	"\fLOG_PURCHASE\x10\x03\x12\x0e\n" +
	"\n" +
	"LOG_REFUND\x10\x04\x12\x14\n" +
	"\x10LOG_SUBSCRIPTION\x10\x05\x12\f\n" +
	"\bLOG_FUSE\x10\x06\x12\x11\n" +
	"\rLOG_DOWNGRADE\x10\a2\xcb\x04\n" +
	"\x0eBillingService\x12b\n" +
	"\rCreateAccount\x12'.mirage.billing.v1.CreateAccountRequest\x1a(.mirage.billing.v1.CreateAccountResponse\x12P\n" +
	"\aDeposit\x12!.mirage.billing.v1.DepositRequest\x1a\".mirage.billing.v1.DepositResponse\x12S\n" +
	"\n" +
	"GetBalance\x12!.mirage.billing.v1.BalanceRequest\x1a\".mirage.billing.v1.BalanceResponse\x12X\n" +
	"\rPurchaseQuota\x12\".mirage.billing.v1.PurchaseRequest\x1a#.mirage.billing.v1.PurchaseResponse\x12_\n" +
	"\x0eGetBillingLogs\x12%.mirage.billing.v1.BillingLogsRequest\x1a&.mirage.billing.v1.BillingLogsResponse\x12s\n" +
	"\x18PurchaseTierSubscription\x12*.mirage.billing.v1.TierSubscriptionRequest\x1a+.mirage.billing.v1.TierSubscriptionResponseB\x18Z\x16mirage-os/api/proto;pbb\x06proto3"

var (
	file_api_proto_billing_proto_rawDescOnce sync.Once
	file_api_proto_billing_proto_rawDescData []byte
)

func file_api_proto_billing_proto_rawDescGZIP() []byte {
	file_api_proto_billing_proto_rawDescOnce.Do(func() {
		file_api_proto_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_billing_proto_rawDesc), len(file_api_proto_billing_proto_rawDesc)))
	})
	return file_api_proto_billing_proto_rawDescData
}

var file_api_proto_billing_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_billing_proto_goTypes = []any{
	(PackageType)(0),                 // 0: mirage.billing.v1.PackageType
	(LogType)(0),                     // 1: mirage.billing.v1.LogType
	(*CreateAccountRequest)(nil),     // 2: mirage.billing.v1.CreateAccountRequest
	(*CreateAccountResponse)(nil),    // 3: mirage.billing.v1.CreateAccountResponse
	(*DepositRequest)(nil),           // 4: mirage.billing.v1.DepositRequest
	(*DepositResponse)(nil),          // 5: mirage.billing.v1.DepositResponse
	(*BalanceRequest)(nil),           // 6: mirage.billing.v1.BalanceRequest
	(*BalanceResponse)(nil),          // 7: mirage.billing.v1.BalanceResponse
	(*QuotaInfo)(nil),                // 8: mirage.billing.v1.QuotaInfo
	(*CellAllocation)(nil),           // 9: mirage.billing.v1.CellAllocation
	(*PurchaseRequest)(nil),          // 10: mirage.billing.v1.PurchaseRequest
	(*PurchaseResponse)(nil),         // 11: mirage.billing.v1.PurchaseResponse
	(*BillingLogsRequest)(nil),       // 12: mirage.billing.v1.BillingLogsRequest
	(*BillingLogsResponse)(nil),      // 13: mirage.billing.v1.BillingLogsResponse
	(*BillingLog)(nil),               // 14: mirage.billing.v1.BillingLog
	(*TierSubscriptionRequest)(nil),  // 15: mirage.billing.v1.TierSubscriptionRequest
	(*TierSubscriptionResponse)(nil), // 16: mirage.billing.v1.TierSubscriptionResponse
}
var file_api_proto_billing_proto_depIdxs = []int32{
	8,  // 0: mirage.billing.v1.BalanceResponse.quota:type_name -> mirage.billing.v1.QuotaInfo
	9,  // 1: mirage.billing.v1.BalanceResponse.cells:type_name -> mirage.billing.v1.CellAllocation
	0,  // 2: mirage.billing.v1.PurchaseRequest.package_type:type_name -> mirage.billing.v1.PackageType
	14, // 3: mirage.billing.v1.BillingLogsResponse.logs:type_name -> mirage.billing.v1.BillingLog
	1,  // 4: mirage.billing.v1.BillingLog.log_type:type_name -> mirage.billing.v1.LogType
	2,  // 5: mirage.billing.v1.BillingService.CreateAccount:input_type -> mirage.billing.v1.CreateAccountRequest
	4,  // 6: mirage.billing.v1.BillingService.Deposit:input_type -> mirage.billing.v1.DepositRequest
	6,  // 7: mirage.billing.v1.BillingService.GetBalance:input_type -> mirage.billing.v1.BalanceRequest
	10, // 8: mirage.billing.v1.BillingService.PurchaseQuota:input_type -> mirage.billing.v1.PurchaseRequest
	12, // 9: mirage.billing.v1.BillingService.GetBillingLogs:input_type -> mirage.billing.v1.BillingLogsRequest
	15, // 10: mirage.billing.v1.BillingService.PurchaseTierSubscription:input_type -> mirage.billing.v1.TierSubscriptionRequest
	3,  // 11: mirage.billing.v1.BillingService.CreateAccount:output_type -> mirage.billing.v1.CreateAccountResponse
	5,  // 12: mirage.billing.v1.BillingService.Deposit:output_type -> mirage.billing.v1.DepositResponse
	7,  // 13: mirage.billing.v1.BillingService.GetBalance:output_type -> mirage.billing.v1.BalanceResponse
	11, // 14: mirage.billing.v1.BillingService.PurchaseQuota:output_type -> mirage.billing.v1.PurchaseResponse
	13, // 15: mirage.billing.v1.BillingService.GetBillingLogs:output_type -> mirage.billing.v1.BillingLogsResponse
	16, // 16: mirage.billing.v1.BillingService.PurchaseTierSubscription:output_type -> mirage.billing.v1.TierSubscriptionResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_billing_proto_init() }
func file_api_proto_billing_proto_init() {
	if File_api_proto_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_billing_proto_rawDesc), len(file_api_proto_billing_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_billing_proto_goTypes,
		DependencyIndexes: file_api_proto_billing_proto_depIdxs,
		EnumInfos:         file_api_proto_billing_proto_enumTypes,
		MessageInfos:      file_api_proto_billing_proto_msgTypes,
	}.Build()
	File_api_proto_billing_proto = out.File
	file_api_proto_billing_proto_goTypes = nil
	file_api_proto_billing_proto_depIdxs = nil
}
