// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/proto/cell.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CellService_RegisterCell_FullMethodName    = "/mirage.cell.v1.CellService/RegisterCell"
	CellService_ListCells_FullMethodName       = "/mirage.cell.v1.CellService/ListCells"
	CellService_AllocateGateway_FullMethodName = "/mirage.cell.v1.CellService/AllocateGateway"
	CellService_HealthCheck_FullMethodName     = "/mirage.cell.v1.CellService/HealthCheck"
	CellService_SwitchCell_FullMethodName      = "/mirage.cell.v1.CellService/SwitchCell"
)

// CellServiceClient is the client API for CellService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 蜂窝管理服务
type CellServiceClient interface {
	// 注册蜂窝
	RegisterCell(ctx context.Context, in *RegisterCellRequest, opts ...grpc.CallOption) (*RegisterCellResponse, error)
	// 查询可用蜂窝
	ListCells(ctx context.Context, in *ListCellsRequest, opts ...grpc.CallOption) (*ListCellsResponse, error)
	// 分配 Gateway 到蜂窝
	AllocateGateway(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*AllocateResponse, error)
	// 蜂窝健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// 切换蜂窝（用户主动或威胁触发）
	SwitchCell(ctx context.Context, in *SwitchCellRequest, opts ...grpc.CallOption) (*SwitchCellResponse, error)
}

type cellServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCellServiceClient(cc grpc.ClientConnInterface) CellServiceClient {
	return &cellServiceClient{cc}
}

func (c *cellServiceClient) RegisterCell(ctx context.Context, in *RegisterCellRequest, opts ...grpc.CallOption) (*RegisterCellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterCellResponse)
	err := c.cc.Invoke(ctx, CellService_RegisterCell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellServiceClient) ListCells(ctx context.Context, in *ListCellsRequest, opts ...grpc.CallOption) (*ListCellsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCellsResponse)
	err := c.cc.Invoke(ctx, CellService_ListCells_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellServiceClient) AllocateGateway(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*AllocateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocateResponse)
	err := c.cc.Invoke(ctx, CellService_AllocateGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, CellService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellServiceClient) SwitchCell(ctx context.Context, in *SwitchCellRequest, opts ...grpc.CallOption) (*SwitchCellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwitchCellResponse)
	err := c.cc.Invoke(ctx, CellService_SwitchCell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CellServiceServer is the server API for CellService service.
// All implementations must embed UnimplementedCellServiceServer
// for forward compatibility.
//
// 蜂窝管理服务
type CellServiceServer interface {
	// 注册蜂窝
	RegisterCell(context.Context, *RegisterCellRequest) (*RegisterCellResponse, error)
	// 查询可用蜂窝
	ListCells(context.Context, *ListCellsRequest) (*ListCellsResponse, error)
	// 分配 Gateway 到蜂窝
	AllocateGateway(context.Context, *AllocateRequest) (*AllocateResponse, error)
	// 蜂窝健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// 切换蜂窝（用户主动或威胁触发）
	SwitchCell(context.Context, *SwitchCellRequest) (*SwitchCellResponse, error)
	mustEmbedUnimplementedCellServiceServer()
}

// UnimplementedCellServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCellServiceServer struct{}

func (UnimplementedCellServiceServer) RegisterCell(context.Context, *RegisterCellRequest) (*RegisterCellResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterCell not implemented")
}
func (UnimplementedCellServiceServer) ListCells(context.Context, *ListCellsRequest) (*ListCellsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCells not implemented")
}
func (UnimplementedCellServiceServer) AllocateGateway(context.Context, *AllocateRequest) (*AllocateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllocateGateway not implemented")
}
func (UnimplementedCellServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedCellServiceServer) SwitchCell(context.Context, *SwitchCellRequest) (*SwitchCellResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SwitchCell not implemented")
}
func (UnimplementedCellServiceServer) mustEmbedUnimplementedCellServiceServer() {}
func (UnimplementedCellServiceServer) testEmbeddedByValue()                     {}

// UnsafeCellServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CellServiceServer will
// result in compilation errors.
type UnsafeCellServiceServer interface {
	mustEmbedUnimplementedCellServiceServer()
}

func RegisterCellServiceServer(s grpc.ServiceRegistrar, srv CellServiceServer) {
	// If the following call panics, it indicates UnimplementedCellServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CellService_ServiceDesc, srv)
}

func _CellService_RegisterCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellServiceServer).RegisterCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellService_RegisterCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellServiceServer).RegisterCell(ctx, req.(*RegisterCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellService_ListCells_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCellsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellServiceServer).ListCells(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellService_ListCells_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellServiceServer).ListCells(ctx, req.(*ListCellsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellService_AllocateGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellServiceServer).AllocateGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellService_AllocateGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellServiceServer).AllocateGateway(ctx, req.(*AllocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellService_SwitchCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellServiceServer).SwitchCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellService_SwitchCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellServiceServer).SwitchCell(ctx, req.(*SwitchCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CellService_ServiceDesc is the grpc.ServiceDesc for CellService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CellService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mirage.cell.v1.CellService",
	HandlerType: (*CellServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterCell",
			Handler:    _CellService_RegisterCell_Handler,
		},
		{
			MethodName: "ListCells",
			Handler:    _CellService_ListCells_Handler,
		},
		{
			MethodName: "AllocateGateway",
			Handler:    _CellService_AllocateGateway_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _CellService_HealthCheck_Handler,
		},
		{
			MethodName: "SwitchCell",
			Handler:    _CellService_SwitchCell_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/cell.proto",
}
