// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: api/proto/cell.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CellLevel int32

const (
	CellLevel_LEVEL_UNKNOWN  CellLevel = 0
	CellLevel_LEVEL_STANDARD CellLevel = 1 // 标准蜂窝
	CellLevel_LEVEL_PLATINUM CellLevel = 2 // 白金蜂窝
	CellLevel_LEVEL_DIAMOND  CellLevel = 3 // 钻石蜂窝
)

// Enum value maps for CellLevel.
var (
	CellLevel_name = map[int32]string{
		0: "LEVEL_UNKNOWN",
		1: "LEVEL_STANDARD",
		2: "LEVEL_PLATINUM",
		3: "LEVEL_DIAMOND",
	}
	CellLevel_value = map[string]int32{
		"LEVEL_UNKNOWN":  0,
		"LEVEL_STANDARD": 1,
		"LEVEL_PLATINUM": 2,
		"LEVEL_DIAMOND":  3,
	}
)

func (x CellLevel) Enum() *CellLevel {
	p := new(CellLevel)
	*p = x
	return p
}

func (x CellLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CellLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_cell_proto_enumTypes[0].Descriptor()
}

func (CellLevel) Type() protoreflect.EnumType {
	return &file_api_proto_cell_proto_enumTypes[0]
}

func (x CellLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CellLevel.Descriptor instead.
func (CellLevel) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_cell_proto_rawDescGZIP(), []int{0}
}

type SwitchReason int32

const (
	SwitchReason_REASON_UNKNOWN             SwitchReason = 0
	SwitchReason_REASON_USER_REQUEST        SwitchReason = 1 // 用户主动切换
	SwitchReason_REASON_THREAT_DETECTED     SwitchReason = 2 // 威胁检测
	SwitchReason_REASON_CELL_OVERLOAD       SwitchReason = 3 // 蜂窝过载
	SwitchReason_REASON_CELL_OFFLINE        SwitchReason = 4 // 蜂窝离线
	SwitchReason_REASON_JURISDICTION_CHANGE SwitchReason = 5 // 司法管辖区变更
)

// Enum value maps for SwitchReason.
var (
	SwitchReason_name = map[int32]string{
		0: "REASON_UNKNOWN",
		1: "REASON_USER_REQUEST",
		2: "REASON_THREAT_DETECTED",
		3: "REASON_CELL_OVERLOAD",
		4: "REASON_CELL_OFFLINE",
		5: "REASON_JURISDICTION_CHANGE",
	}
	SwitchReason_value = map[string]int32{
		"REASON_UNKNOWN":             0,
		"REASON_USER_REQUEST":        1,
		"REASON_THREAT_DETECTED":     2,
		"REASON_CELL_OVERLOAD":       3,
		"REASON_CELL_OFFLINE":        4,
		"REASON_JURISDICTION_CHANGE": 5,
	}
)

func (x SwitchReason) Enum() *SwitchReason {
	p := new(SwitchReason)
	*p = x
	return p
}

func (x SwitchReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SwitchReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_cell_proto_enumTypes[1].Descriptor()
}

func (SwitchReason) Type() protoreflect.EnumType {
	return &file_api_proto_cell_proto_enumTypes[1]
}

func (x SwitchReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SwitchReason.Descriptor instead.
func (SwitchReason) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_cell_proto_rawDescGZIP(), []int{1}
}

type RegisterCellRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CellId         string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`                           // 蜂窝 ID
	CellName       string                 `protobuf:"bytes,2,opt,name=cell_name,json=cellName,proto3" json:"cell_name,omitempty"`                     // 蜂窝名称
	Level          CellLevel              `protobuf:"varint,3,opt,name=level,proto3,enum=mirage.cell.v1.CellLevel" json:"level,omitempty"`            // 蜂窝等级
	Location       *GeoLocation           `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`                                     // 地理位置
	CostMultiplier float32                `protobuf:"fixed32,5,opt,name=cost_multiplier,json=costMultiplier,proto3" json:"cost_multiplier,omitempty"` // 成本倍率
	MaxGateways    uint32                 `protobuf:"varint,6,opt,name=max_gateways,json=maxGateways,proto3" json:"max_gateways,omitempty"`           // 最大 Gateway 数量
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterCellRequest) Reset() {
	*x = RegisterCellRequest{}
	mi := &file_api_proto_cell_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCellRequest) ProtoMessage() {}

func (x *RegisterCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cell_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCellRequest.ProtoReflect.Descriptor instead.
func (*RegisterCellRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cell_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterCellRequest) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *RegisterCellRequest) GetCellName() string {
	if x != nil {
		return x.CellName
	}
	return ""
}

func (x *RegisterCellRequest) GetLevel() CellLevel {
	if x != nil {
		return x.Level
	}
	return CellLevel_LEVEL_UNKNOWN
}

func (x *RegisterCellRequest) GetLocation() *GeoLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *RegisterCellRequest) GetCostMultiplier() float32 {
	if x != nil {
		return x.CostMultiplier
	}
	return 0
}

func (x *RegisterCellRequest) GetMaxGateways() uint32 {
	if x != nil {
		return x.MaxGateways
	}
	return 0
}

type GeoLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`           // 国家代码（ISO 3166-1）
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`             // 地区（如 "US-West"）
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`                 // 城市
	Latitude      float32                `protobuf:"fixed32,4,opt,name=latitude,proto3" json:"latitude,omitempty"`       // 纬度
	Longitude     float32                `protobuf:"fixed32,5,opt,name=longitude,proto3" json:"longitude,omitempty"`     // 经度
	Jurisdiction  string                 `protobuf:"bytes,6,opt,name=jurisdiction,proto3" json:"jurisdiction,omitempty"` // 司法管辖区
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoLocation) Reset() {
	*x = GeoLocation{}
	mi := &file_api_proto_cell_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoLocation) ProtoMessage() {}

func (x *GeoLocation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cell_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoLocation.ProtoReflect.Descriptor instead.
func (*GeoLocation) Descriptor() ([]byte, []int) {
	return file_api_proto_cell_proto_rawDescGZIP(), []int{1}
}

func (x *GeoLocation) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GeoLocation) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GeoLocation) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GeoLocation) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeoLocation) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeoLocation) GetJurisdiction() string {
	if x != nil {
		return x.Jurisdiction
	}
	return ""
}

type RegisterCellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CellId        string                 `protobuf:"bytes,3,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`                    // 蜂窝 ID
	RegisteredAt  int64                  `protobuf:"varint,4,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"` // 注册时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCellResponse) Reset() {
	*x = RegisterCellResponse{}
	mi := &file_api_proto_cell_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCellResponse) ProtoMessage() {}

func (x *RegisterCellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cell_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCellResponse.ProtoReflect.Descriptor instead.
func (*RegisterCellResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cell_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterCellResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterCellResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterCellResponse) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *RegisterCellResponse) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

type ListCellsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         CellLevel              `protobuf:"varint,1,opt,name=level,proto3,enum=mirage.cell.v1.CellLevel" json:"level,omitempty"` // 筛选等级（可选）
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`                            // 筛选国家（可选）
	OnlineOnly    bool                   `protobuf:"varint,3,opt,name=online_only,json=onlineOnly,proto3" json:"online_only,omitempty"`   // 仅在线蜂窝
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCellsRequest) Reset() {
	*x = ListCellsRequest{}
	mi := &file_api_proto_cell_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCellsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCellsRequest) ProtoMessage() {}

func (x *ListCellsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cell_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCellsRequest.ProtoReflect.Descriptor instead.
func (*ListCellsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cell_proto_rawDescGZIP(), []int{3}
}

func (x *ListCellsRequest) GetLevel() CellLevel {
	if x != nil {
		return x.Level
	}
	return CellLevel_LEVEL_UNKNOWN
}

func (x *ListCellsRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ListCellsRequest) GetOnlineOnly() bool {
	if x != nil {
		return x.OnlineOnly
	}
	return false
}

type ListCellsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Cells         []*CellInfo            `protobuf:"bytes,3,rep,name=cells,proto3" json:"cells,omitempty"` // 蜂窝列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCellsResponse) Reset() {
	*x = ListCellsResponse{}
	mi := &file_api_proto_cell_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCellsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCellsResponse) ProtoMessage() {}

func (x *ListCellsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cell_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCellsResponse.ProtoReflect.Descriptor instead.
func (*ListCellsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cell_proto_rawDescGZIP(), []int{4}
}

func (x *ListCellsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListCellsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListCellsResponse) GetCells() []*CellInfo {
	if x != nil {
		return x.Cells
	}
	return nil
}

type CellInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CellId         string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`                           // 蜂窝 ID
	CellName       string                 `protobuf:"bytes,2,opt,name=cell_name,json=cellName,proto3" json:"cell_name,omitempty"`                     // 蜂窝名称
	Level          CellLevel              `protobuf:"varint,3,opt,name=level,proto3,enum=mirage.cell.v1.CellLevel" json:"level,omitempty"`            // 等级
	Location       *GeoLocation           `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`                                     // 位置
	Status         *CellStatus            `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                         // 状态
	GatewayCount   uint32                 `protobuf:"varint,6,opt,name=gateway_count,json=gatewayCount,proto3" json:"gateway_count,omitempty"`        // Gateway 数量
	MaxGateways    uint32                 `protobuf:"varint,7,opt,name=max_gateways,json=maxGateways,proto3" json:"max_gateways,omitempty"`           // 最大容量
	CostMultiplier float32                `protobuf:"fixed32,8,opt,name=cost_multiplier,json=costMultiplier,proto3" json:"cost_multiplier,omitempty"` // 成本倍率
	LoadPercent    float32                `protobuf:"fixed32,9,opt,name=load_percent,json=loadPercent,proto3" json:"load_percent,omitempty"`          // 负载率 (0-100)
	LastHeartbeat  int64                  `protobuf:"varint,10,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`    // 最后心跳时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CellInfo) Reset() {
	*x = CellInfo{}
	mi := &file_api_proto_cell_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellInfo) ProtoMessage() {}

func (x *CellInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cell_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellInfo.ProtoReflect.Descriptor instead.
func (*CellInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_cell_proto_rawDescGZIP(), []int{5}
}

func (x *CellInfo) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *CellInfo) GetCellName() string {
	if x != nil {
		return x.CellName
	}
	return ""
}

func (x *CellInfo) GetLevel() CellLevel {
	if x != nil {
		return x.Level
	}
	return CellLevel_LEVEL_UNKNOWN
}

func (x *CellInfo) GetLocation() *GeoLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *CellInfo) GetStatus() *CellStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CellInfo) GetGatewayCount() uint32 {
	if x != nil {
		return x.GatewayCount
	}
	return 0
}

func (x *CellInfo) GetMaxGateways() uint32 {
	if x != nil {
		return x.MaxGateways
	}
	return 0
}

func (x *CellInfo) GetCostMultiplier() float32 {
	if x != nil {
		return x.CostMultiplier
	}
	return 0
}

func (x *CellInfo) GetLoadPercent() float32 {
	if x != nil {
		return x.LoadPercent
	}
	return 0
}

func (x *CellInfo) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

type CellStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Online            bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`                                                  // 是否在线
	ActiveConnections uint32                 `protobuf:"varint,2,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`   // 活跃连接数
	TotalBandwidthBps uint64                 `protobuf:"varint,3,opt,name=total_bandwidth_bps,json=totalBandwidthBps,proto3" json:"total_bandwidth_bps,omitempty"` // 总带宽（bps）
	ThreatLevel       uint32                 `protobuf:"varint,4,opt,name=threat_level,json=threatLevel,proto3" json:"threat_level,omitempty"`                     // 威胁等级 (0-5)
	BlockedIps        []string               `protobuf:"bytes,5,rep,name=blocked_ips,json=blockedIps,proto3" json:"blocked_ips,omitempty"`                         // 封禁 IP 列表
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CellStatus) Reset() {
	*x = CellStatus{}
	mi := &file_api_proto_cell_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellStatus) ProtoMessage() {}

func (x *CellStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cell_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellStatus.ProtoReflect.Descriptor instead.
func (*CellStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_cell_proto_rawDescGZIP(), []int{6}
}

func (x *CellStatus) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *CellStatus) GetActiveConnections() uint32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *CellStatus) GetTotalBandwidthBps() uint64 {
	if x != nil {
		return x.TotalBandwidthBps
	}
	return 0
}

func (x *CellStatus) GetThreatLevel() uint32 {
	if x != nil {
		return x.ThreatLevel
	}
	return 0
}

func (x *CellStatus) GetBlockedIps() []string {
	if x != nil {
		return x.BlockedIps
	}
	return nil
}

type AllocateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                        // 用户 ID
	GatewayId        string                 `protobuf:"bytes,2,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`                                               // Gateway ID
	PreferredLevel   CellLevel              `protobuf:"varint,3,opt,name=preferred_level,json=preferredLevel,proto3,enum=mirage.cell.v1.CellLevel" json:"preferred_level,omitempty"` // 偏好等级
	PreferredCountry string                 `protobuf:"bytes,4,opt,name=preferred_country,json=preferredCountry,proto3" json:"preferred_country,omitempty"`                          // 偏好国家
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AllocateRequest) Reset() {
	*x = AllocateRequest{}
	mi := &file_api_proto_cell_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateRequest) ProtoMessage() {}

func (x *AllocateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cell_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateRequest.ProtoReflect.Descriptor instead.
func (*AllocateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cell_proto_rawDescGZIP(), []int{7}
}

func (x *AllocateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AllocateRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *AllocateRequest) GetPreferredLevel() CellLevel {
	if x != nil {
		return x.PreferredLevel
	}
	return CellLevel_LEVEL_UNKNOWN
}

func (x *AllocateRequest) GetPreferredCountry() string {
	if x != nil {
		return x.PreferredCountry
	}
	return ""
}

type AllocateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CellId          string                 `protobuf:"bytes,3,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`                            // 分配的蜂窝 ID
	CellInfo        *CellInfo              `protobuf:"bytes,4,opt,name=cell_info,json=cellInfo,proto3" json:"cell_info,omitempty"`                      // 蜂窝信息
	ConnectionToken string                 `protobuf:"bytes,5,opt,name=connection_token,json=connectionToken,proto3" json:"connection_token,omitempty"` // 连接令牌
	AllocatedAt     int64                  `protobuf:"varint,6,opt,name=allocated_at,json=allocatedAt,proto3" json:"allocated_at,omitempty"`            // 分配时间
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AllocateResponse) Reset() {
	*x = AllocateResponse{}
	mi := &file_api_proto_cell_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateResponse) ProtoMessage() {}

func (x *AllocateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cell_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateResponse.ProtoReflect.Descriptor instead.
func (*AllocateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cell_proto_rawDescGZIP(), []int{8}
}

func (x *AllocateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AllocateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AllocateResponse) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *AllocateResponse) GetCellInfo() *CellInfo {
	if x != nil {
		return x.CellInfo
	}
	return nil
}

func (x *AllocateResponse) GetConnectionToken() string {
	if x != nil {
		return x.ConnectionToken
	}
	return ""
}

func (x *AllocateResponse) GetAllocatedAt() int64 {
	if x != nil {
		return x.AllocatedAt
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CellId        string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"` // 蜂窝 ID（可选，空则检查全部）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_cell_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cell_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cell_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckRequest) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	HealthStatus  []*CellHealth          `protobuf:"bytes,3,rep,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_cell_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cell_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cell_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetHealthStatus() []*CellHealth {
	if x != nil {
		return x.HealthStatus
	}
	return nil
}

type CellHealth struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CellId          string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`                            // 蜂窝 ID
	Healthy         bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`                                       // 是否健康
	GatewayCount    uint32                 `protobuf:"varint,3,opt,name=gateway_count,json=gatewayCount,proto3" json:"gateway_count,omitempty"`         // Gateway 数量
	FailedGateways  uint32                 `protobuf:"varint,4,opt,name=failed_gateways,json=failedGateways,proto3" json:"failed_gateways,omitempty"`   // 失败 Gateway 数量
	AvgLatencyMs    float32                `protobuf:"fixed32,5,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`      // 平均延迟（毫秒）
	ThreatCount_24H uint32                 `protobuf:"varint,6,opt,name=threat_count_24h,json=threatCount24h,proto3" json:"threat_count_24h,omitempty"` // 24小时威胁计数
	LastCheck       int64                  `protobuf:"varint,7,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`                  // 最后检查时间
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CellHealth) Reset() {
	*x = CellHealth{}
	mi := &file_api_proto_cell_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellHealth) ProtoMessage() {}

func (x *CellHealth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cell_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellHealth.ProtoReflect.Descriptor instead.
func (*CellHealth) Descriptor() ([]byte, []int) {
	return file_api_proto_cell_proto_rawDescGZIP(), []int{11}
}

func (x *CellHealth) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *CellHealth) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *CellHealth) GetGatewayCount() uint32 {
	if x != nil {
		return x.GatewayCount
	}
	return 0
}

func (x *CellHealth) GetFailedGateways() uint32 {
	if x != nil {
		return x.FailedGateways
	}
	return 0
}

func (x *CellHealth) GetAvgLatencyMs() float32 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *CellHealth) GetThreatCount_24H() uint32 {
	if x != nil {
		return x.ThreatCount_24H
	}
	return 0
}

func (x *CellHealth) GetLastCheck() int64 {
	if x != nil {
		return x.LastCheck
	}
	return 0
}

type SwitchCellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                        // 用户 ID
	GatewayId     string                 `protobuf:"bytes,2,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`               // Gateway ID
	CurrentCellId string                 `protobuf:"bytes,3,opt,name=current_cell_id,json=currentCellId,proto3" json:"current_cell_id,omitempty"` // 当前蜂窝 ID
	TargetCellId  string                 `protobuf:"bytes,4,opt,name=target_cell_id,json=targetCellId,proto3" json:"target_cell_id,omitempty"`    // 目标蜂窝 ID（可选）
	Reason        SwitchReason           `protobuf:"varint,5,opt,name=reason,proto3,enum=mirage.cell.v1.SwitchReason" json:"reason,omitempty"`    // 切换原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchCellRequest) Reset() {
	*x = SwitchCellRequest{}
	mi := &file_api_proto_cell_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchCellRequest) ProtoMessage() {}

func (x *SwitchCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cell_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchCellRequest.ProtoReflect.Descriptor instead.
func (*SwitchCellRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cell_proto_rawDescGZIP(), []int{12}
}

func (x *SwitchCellRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SwitchCellRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *SwitchCellRequest) GetCurrentCellId() string {
	if x != nil {
		return x.CurrentCellId
	}
	return ""
}

func (x *SwitchCellRequest) GetTargetCellId() string {
	if x != nil {
		return x.TargetCellId
	}
	return ""
}

func (x *SwitchCellRequest) GetReason() SwitchReason {
	if x != nil {
		return x.Reason
	}
	return SwitchReason_REASON_UNKNOWN
}

type SwitchCellResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NewCellId       string                 `protobuf:"bytes,3,opt,name=new_cell_id,json=newCellId,proto3" json:"new_cell_id,omitempty"`                 // 新蜂窝 ID
	NewCellInfo     *CellInfo              `protobuf:"bytes,4,opt,name=new_cell_info,json=newCellInfo,proto3" json:"new_cell_info,omitempty"`           // 新蜂窝信息
	ConnectionToken string                 `protobuf:"bytes,5,opt,name=connection_token,json=connectionToken,proto3" json:"connection_token,omitempty"` // 新连接令牌
	SwitchedAt      int64                  `protobuf:"varint,6,opt,name=switched_at,json=switchedAt,proto3" json:"switched_at,omitempty"`               // 切换时间
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SwitchCellResponse) Reset() {
	*x = SwitchCellResponse{}
	mi := &file_api_proto_cell_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchCellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchCellResponse) ProtoMessage() {}

func (x *SwitchCellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cell_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchCellResponse.ProtoReflect.Descriptor instead.
func (*SwitchCellResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cell_proto_rawDescGZIP(), []int{13}
}

func (x *SwitchCellResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SwitchCellResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SwitchCellResponse) GetNewCellId() string {
	if x != nil {
		return x.NewCellId
	}
	return ""
}

func (x *SwitchCellResponse) GetNewCellInfo() *CellInfo {
	if x != nil {
		return x.NewCellInfo
	}
	return nil
}

func (x *SwitchCellResponse) GetConnectionToken() string {
	if x != nil {
		return x.ConnectionToken
	}
	return ""
}

func (x *SwitchCellResponse) GetSwitchedAt() int64 {
	if x != nil {
		return x.SwitchedAt
	}
	return 0
}

var File_api_proto_cell_proto protoreflect.FileDescriptor

const file_api_proto_cell_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/cell.proto\x12\x0emirage.cell.v1\"\x81\x02\n" +
	"\x13RegisterCellRequest\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\x12\x1b\n" +
	"\tcell_name\x18\x02 \x01(\tR\bcellName\x12/\n" +
	"\x05level\x18\x03 \x01(\x0e2\x19.mirage.cell.v1.CellLevelR\x05level\x127\n" +
	"\blocation\x18\x04 \x01(\v2\x1b.mirage.cell.v1.GeoLocationR\blocation\x12'\n" +
	"\x0fcost_multiplier\x18\x05 \x01(\x02R\x0ecostMultiplier\x12!\n" +
	"\fmax_gateways\x18\x06 \x01(\rR\vmaxGateways\"\xb1\x01\n" +
	"\vGeoLocation\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x02R\tlongitude\x12\"\n" +
	"\fjurisdiction\x18\x06 \x01(\tR\fjurisdiction\"\x88\x01\n" +
	"\x14RegisterCellResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\acell_id\x18\x03 \x01(\tR\x06cellId\x12#\n" +
	"\rregistered_at\x18\x04 \x01(\x03R\fregisteredAt\"~\n" +
	"\x10ListCellsRequest\x12/\n" +
	"\x05level\x18\x01 \x01(\x0e2\x19.mirage.cell.v1.CellLevelR\x05level\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x1f\n" +
	"\vonline_only\x18\x03 \x01(\bR\n" +
	"onlineOnly\"w\n" +
	"\x11ListCellsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x05cells\x18\x03 \x03(\v2\x18.mirage.cell.v1.CellInfoR\x05cells\"\x99\x03\n" +
	"\bCellInfo\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\x12\x1b\n" +
	"\tcell_name\x18\x02 \x01(\tR\bcellName\x12/\n" +
	"\x05level\x18\x03 \x01(\x0e2\x19.mirage.cell.v1.CellLevelR\x05level\x127\n" +
	"\blocation\x18\x04 \x01(\v2\x1b.mirage.cell.v1.GeoLocationR\blocation\x122\n" +
	"\x06status\x18\x05 \x01(\v2\x1a.mirage.cell.v1.CellStatusR\x06status\x12#\n" +
	"\rgateway_count\x18\x06 \x01(\rR\fgatewayCount\x12!\n" +
	"\fmax_gateways\x18\a \x01(\rR\vmaxGateways\x12'\n" +
	"\x0fcost_multiplier\x18\b \x01(\x02R\x0ecostMultiplier\x12!\n" +
	"\fload_percent\x18\t \x01(\x02R\vloadPercent\x12%\n" +
	"\x0elast_heartbeat\x18\n" +
	" \x01(\x03R\rlastHeartbeat\"\xc7\x01\n" +
	"\n" +
	"CellStatus\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online\x12-\n" +
	"\x12active_connections\x18\x02 \x01(\rR\x11activeConnections\x12.\n" +
	"\x13total_bandwidth_bps\x18\x03 \x01(\x04R\x11totalBandwidthBps\x12!\n" +
	"\fthreat_level\x18\x04 \x01(\rR\vthreatLevel\x12\x1f\n" +
	"\vblocked_ips\x18\x05 \x03(\tR\n" +
	"blockedIps\"\xba\x01\n" +
	"\x0fAllocateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x02 \x01(\tR\tgatewayId\x12B\n" +
	"\x0fpreferred_level\x18\x03 \x01(\x0e2\x19.mirage.cell.v1.CellLevelR\x0epreferredLevel\x12+\n" +
	"\x11preferred_country\x18\x04 \x01(\tR\x10preferredCountry\"\xe4\x01\n" +
	"\x10AllocateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\acell_id\x18\x03 \x01(\tR\x06cellId\x125\n" +
	"\tcell_info\x18\x04 \x01(\v2\x18.mirage.cell.v1.CellInfoR\bcellInfo\x12)\n" +
	"\x10connection_token\x18\x05 \x01(\tR\x0fconnectionToken\x12!\n" +
	"\fallocated_at\x18\x06 \x01(\x03R\vallocatedAt\"-\n" +
	"\x12HealthCheckRequest\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\"\x8a\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12?\n" +
	"\rhealth_status\x18\x03 \x03(\v2\x1a.mirage.cell.v1.CellHealthR\fhealthStatus\"\xfc\x01\n" +
	"\n" +
	"CellHealth\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\x12#\n" +
	"\rgateway_count\x18\x03 \x01(\rR\fgatewayCount\x12'\n" +
	"\x0ffailed_gateways\x18\x04 \x01(\rR\x0efailedGateways\x12$\n" +
	"\x0eavg_latency_ms\x18\x05 \x01(\x02R\favgLatencyMs\x12(\n" +
	"\x10threat_count_24h\x18\x06 \x01(\rR\x0ethreatCount24h\x12\x1d\n" +
	"\n" +
	"last_check\x18\a \x01(\x03R\tlastCheck\"\xcf\x01\n" +
	"\x11SwitchCellRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x02 \x01(\tR\tgatewayId\x12&\n" +
	"\x0fcurrent_cell_id\x18\x03 \x01(\tR\rcurrentCellId\x12$\n" +
	"\x0etarget_cell_id\x18\x04 \x01(\tR\ftargetCellId\x124\n" +
	"\x06reason\x18\x05 \x01(\x0e2\x1c.mirage.cell.v1.SwitchReasonR\x06reason\"\xf2\x01\n" +
	"\x12SwitchCellResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\vnew_cell_id\x18\x03 \x01(\tR\tnewCellId\x12<\n" +
	"\rnew_cell_info\x18\x04 \x01(\v2\x18.mirage.cell.v1.CellInfoR\vnewCellInfo\x12)\n" +
	"\x10connection_token\x18\x05 \x01(\tR\x0fconnectionToken\x12\x1f\n" +
	"\vswitched_at\x18\x06 \x01(\x03R\n" +
	"switchedAt*Y\n" +
	"\tCellLevel\x12\x11\n" +
	"\rLEVEL_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eLEVEL_STANDARD\x10\x01\x12\x12\n" +
	"\x0eLEVEL_PLATINUM\x10\x02\x12\x11\n" +
	"\rLEVEL_DIAMOND\x10\x03*\xaa\x01\n" +
	"\fSwitchReason\x12\x12\n" +
	"\x0eREASON_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13REASON_USER_REQUEST\x10\x01\x12\x1a\n" +
	"\x16REASON_THREAT_DETECTED\x10\x02\x12\x18\n" +
	"\x14REASON_CELL_OVERLOAD\x10\x03\x12\x17\n" +
	"\x13REASON_CELL_OFFLINE\x10\x04\x12\x1e\n" +
	"\x1aREASON_JURISDICTION_CHANGE\x10\x052\xbd\x03\n" +
	"\vCellService\x12Y\n" +
	"\fRegisterCell\x12#.mirage.cell.v1.RegisterCellRequest\x1a$.mirage.cell.v1.RegisterCellResponse\x12P\n" +
	"\tListCells\x12 .mirage.cell.v1.ListCellsRequest\x1a!.mirage.cell.v1.ListCellsResponse\x12T\n" +
	"\x0fAllocateGateway\x12\x1f.mirage.cell.v1.AllocateRequest\x1a .mirage.cell.v1.AllocateResponse\x12V\n" +
	"\vHealthCheck\x12\".mirage.cell.v1.HealthCheckRequest\x1a#.mirage.cell.v1.HealthCheckResponse\x12S\n" +
	"\n" +
	"SwitchCell\x12!.mirage.cell.v1.SwitchCellRequest\x1a\".mirage.cell.v1.SwitchCellResponseB\x18Z\x16mirage-os/api/proto;pbb\x06proto3"

var (
	file_api_proto_cell_proto_rawDescOnce sync.Once
	file_api_proto_cell_proto_rawDescData []byte
)

func file_api_proto_cell_proto_rawDescGZIP() []byte {
	file_api_proto_cell_proto_rawDescOnce.Do(func() {
		file_api_proto_cell_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cell_proto_rawDesc), len(file_api_proto_cell_proto_rawDesc)))
	})
	return file_api_proto_cell_proto_rawDescData
}

var file_api_proto_cell_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_cell_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_cell_proto_goTypes = []any{
	(CellLevel)(0),               // 0: mirage.cell.v1.CellLevel
	(SwitchReason)(0),            // 1: mirage.cell.v1.SwitchReason
	(*RegisterCellRequest)(nil),  // 2: mirage.cell.v1.RegisterCellRequest
	(*GeoLocation)(nil),          // 3: mirage.cell.v1.GeoLocation
	(*RegisterCellResponse)(nil), // 4: mirage.cell.v1.RegisterCellResponse
	(*ListCellsRequest)(nil),     // 5: mirage.cell.v1.ListCellsRequest
	(*ListCellsResponse)(nil),    // 6: mirage.cell.v1.ListCellsResponse
	(*CellInfo)(nil),             // 7: mirage.cell.v1.CellInfo
	(*CellStatus)(nil),           // 8: mirage.cell.v1.CellStatus
	(*AllocateRequest)(nil),      // 9: mirage.cell.v1.AllocateRequest
	(*AllocateResponse)(nil),     // 10: mirage.cell.v1.AllocateResponse
	(*HealthCheckRequest)(nil),   // 11: mirage.cell.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),  // 12: mirage.cell.v1.HealthCheckResponse
	(*CellHealth)(nil),           // 13: mirage.cell.v1.CellHealth
	(*SwitchCellRequest)(nil),    // 14: mirage.cell.v1.SwitchCellRequest
	(*SwitchCellResponse)(nil),   // 15: mirage.cell.v1.SwitchCellResponse
}
var file_api_proto_cell_proto_depIdxs = []int32{
	0,  // 0: mirage.cell.v1.RegisterCellRequest.level:type_name -> mirage.cell.v1.CellLevel
	3,  // 1: mirage.cell.v1.RegisterCellRequest.location:type_name -> mirage.cell.v1.GeoLocation
	0,  // 2: mirage.cell.v1.ListCellsRequest.level:type_name -> mirage.cell.v1.CellLevel
	7,  // 3: mirage.cell.v1.ListCellsResponse.cells:type_name -> mirage.cell.v1.CellInfo
	0,  // 4: mirage.cell.v1.CellInfo.level:type_name -> mirage.cell.v1.CellLevel
	3,  // 5: mirage.cell.v1.CellInfo.location:type_name -> mirage.cell.v1.GeoLocation
	8,  // 6: mirage.cell.v1.CellInfo.status:type_name -> mirage.cell.v1.CellStatus
	0,  // 7: mirage.cell.v1.AllocateRequest.preferred_level:type_name -> mirage.cell.v1.CellLevel
	7,  // 8: mirage.cell.v1.AllocateResponse.cell_info:type_name -> mirage.cell.v1.CellInfo
	13, // 9: mirage.cell.v1.HealthCheckResponse.health_status:type_name -> mirage.cell.v1.CellHealth
	1,  // 10: mirage.cell.v1.SwitchCellRequest.reason:type_name -> mirage.cell.v1.SwitchReason
	7,  // 11: mirage.cell.v1.SwitchCellResponse.new_cell_info:type_name -> mirage.cell.v1.CellInfo
	2,  // 12: mirage.cell.v1.CellService.RegisterCell:input_type -> mirage.cell.v1.RegisterCellRequest
	5,  // 13: mirage.cell.v1.CellService.ListCells:input_type -> mirage.cell.v1.ListCellsRequest
	9,  // 14: mirage.cell.v1.CellService.AllocateGateway:input_type -> mirage.cell.v1.AllocateRequest
	11, // 15: mirage.cell.v1.CellService.HealthCheck:input_type -> mirage.cell.v1.HealthCheckRequest
	14, // 16: mirage.cell.v1.CellService.SwitchCell:input_type -> mirage.cell.v1.SwitchCellRequest
	4,  // 17: mirage.cell.v1.CellService.RegisterCell:output_type -> mirage.cell.v1.RegisterCellResponse
	6,  // 18: mirage.cell.v1.CellService.ListCells:output_type -> mirage.cell.v1.ListCellsResponse
	10, // 19: mirage.cell.v1.CellService.AllocateGateway:output_type -> mirage.cell.v1.AllocateResponse
	12, // 20: mirage.cell.v1.CellService.HealthCheck:output_type -> mirage.cell.v1.HealthCheckResponse
	15, // 21: mirage.cell.v1.CellService.SwitchCell:output_type -> mirage.cell.v1.SwitchCellResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_proto_cell_proto_init() }
func file_api_proto_cell_proto_init() {
	if File_api_proto_cell_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cell_proto_rawDesc), len(file_api_proto_cell_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_cell_proto_goTypes,
		DependencyIndexes: file_api_proto_cell_proto_depIdxs,
		EnumInfos:         file_api_proto_cell_proto_enumTypes,
		MessageInfos:      file_api_proto_cell_proto_msgTypes,
	}.Build()
	File_api_proto_cell_proto = out.File
	file_api_proto_cell_proto_goTypes = nil
	file_api_proto_cell_proto_depIdxs = nil
}
