// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: api/proto/gateway.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ThreatType int32

const (
	ThreatType_THREAT_UNKNOWN        ThreatType = 0
	ThreatType_THREAT_ACTIVE_PROBING ThreatType = 1 // 主动探测
	ThreatType_THREAT_JA4_SCAN       ThreatType = 2 // JA4 指纹扫描
	ThreatType_THREAT_SNI_PROBE      ThreatType = 3 // SNI 探测
	ThreatType_THREAT_DPI_INSPECTION ThreatType = 4 // DPI 深度检测
	ThreatType_THREAT_TIMING_ATTACK  ThreatType = 5 // 时序攻击
	ThreatType_THREAT_REPLAY_ATTACK  ThreatType = 6 // 重放攻击
)

// Enum value maps for ThreatType.
var (
	ThreatType_name = map[int32]string{
		0: "THREAT_UNKNOWN",
		1: "THREAT_ACTIVE_PROBING",
		2: "THREAT_JA4_SCAN",
		3: "THREAT_SNI_PROBE",
		4: "THREAT_DPI_INSPECTION",
		5: "THREAT_TIMING_ATTACK",
		6: "THREAT_REPLAY_ATTACK",
	}
	ThreatType_value = map[string]int32{
		"THREAT_UNKNOWN":        0,
		"THREAT_ACTIVE_PROBING": 1,
		"THREAT_JA4_SCAN":       2,
		"THREAT_SNI_PROBE":      3,
		"THREAT_DPI_INSPECTION": 4,
		"THREAT_TIMING_ATTACK":  5,
		"THREAT_REPLAY_ATTACK":  6,
	}
)

func (x ThreatType) Enum() *ThreatType {
	p := new(ThreatType)
	*p = x
	return p
}

func (x ThreatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThreatType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_gateway_proto_enumTypes[0].Descriptor()
}

func (ThreatType) Type() protoreflect.EnumType {
	return &file_api_proto_gateway_proto_enumTypes[0]
}

func (x ThreatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThreatType.Descriptor instead.
func (ThreatType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{0}
}

type ThreatAction int32

const (
	ThreatAction_ACTION_NONE               ThreatAction = 0 // 无动作
	ThreatAction_ACTION_INCREASE_DEFENSE   ThreatAction = 1 // 提升防御
	ThreatAction_ACTION_BLOCK_IP           ThreatAction = 2 // 封禁 IP
	ThreatAction_ACTION_SWITCH_CELL        ThreatAction = 3 // 切换蜂窝
	ThreatAction_ACTION_EMERGENCY_SHUTDOWN ThreatAction = 4 // 紧急关闭
)

// Enum value maps for ThreatAction.
var (
	ThreatAction_name = map[int32]string{
		0: "ACTION_NONE",
		1: "ACTION_INCREASE_DEFENSE",
		2: "ACTION_BLOCK_IP",
		3: "ACTION_SWITCH_CELL",
		4: "ACTION_EMERGENCY_SHUTDOWN",
	}
	ThreatAction_value = map[string]int32{
		"ACTION_NONE":               0,
		"ACTION_INCREASE_DEFENSE":   1,
		"ACTION_BLOCK_IP":           2,
		"ACTION_SWITCH_CELL":        3,
		"ACTION_EMERGENCY_SHUTDOWN": 4,
	}
)

func (x ThreatAction) Enum() *ThreatAction {
	p := new(ThreatAction)
	*p = x
	return p
}

func (x ThreatAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThreatAction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_gateway_proto_enumTypes[1].Descriptor()
}

func (ThreatAction) Type() protoreflect.EnumType {
	return &file_api_proto_gateway_proto_enumTypes[1]
}

func (x ThreatAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThreatAction.Descriptor instead.
func (ThreatAction) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{1}
}

type HeartbeatRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GatewayId          string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`                               // Gateway 唯一标识
	Version            string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                                                    // Gateway 版本
	CurrentThreatLevel uint32                 `protobuf:"varint,3,opt,name=current_threat_level,json=currentThreatLevel,proto3" json:"current_threat_level,omitempty"` // 当前威胁等级 (0-5)
	Status             *GatewayStatus         `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                                      // Gateway 状态
	Resource           *ResourceUsage         `protobuf:"bytes,5,opt,name=resource,proto3" json:"resource,omitempty"`                                                  // 资源使用情况
	Timestamp          int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                               // 时间戳（Unix 秒）
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *HeartbeatRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HeartbeatRequest) GetCurrentThreatLevel() uint32 {
	if x != nil {
		return x.CurrentThreatLevel
	}
	return 0
}

func (x *HeartbeatRequest) GetStatus() *GatewayStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *HeartbeatRequest) GetResource() *ResourceUsage {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GatewayStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Online            bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`                                                // 是否在线
	ActiveConnections uint32                 `protobuf:"varint,2,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"` // 活跃连接数
	UptimeSeconds     uint64                 `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`             // 运行时长（秒）
	CellId            string                 `protobuf:"bytes,4,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`                                   // 所属蜂窝 ID
	Region            string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`                                                 // 地理区域（如 "US-West"）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GatewayStatus) Reset() {
	*x = GatewayStatus{}
	mi := &file_api_proto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayStatus) ProtoMessage() {}

func (x *GatewayStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayStatus.ProtoReflect.Descriptor instead.
func (*GatewayStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayStatus) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *GatewayStatus) GetActiveConnections() uint32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *GatewayStatus) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *GatewayStatus) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *GatewayStatus) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type ResourceUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float32                `protobuf:"fixed32,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`      // CPU 占用率 (0-100)
	MemoryBytes   uint64                 `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`    // 内存占用（字节）
	BandwidthBps  uint64                 `protobuf:"varint,3,opt,name=bandwidth_bps,json=bandwidthBps,proto3" json:"bandwidth_bps,omitempty"` // 带宽使用（bps）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	mi := &file_api_proto_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsage.ProtoReflect.Descriptor instead.
func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceUsage) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceUsage) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceUsage) GetBandwidthBps() uint64 {
	if x != nil {
		return x.BandwidthBps
	}
	return 0
}

type HeartbeatResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Success               bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                                            // 是否成功
	Message               string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                             // 响应消息
	DefenseConfig         *DefenseConfig         `protobuf:"bytes,3,opt,name=defense_config,json=defenseConfig,proto3" json:"defense_config,omitempty"`                            // 新的防御配置
	RemainingQuota        uint64                 `protobuf:"varint,4,opt,name=remaining_quota,json=remainingQuota,proto3" json:"remaining_quota,omitempty"`                        // 剩余配额（字节）
	NextHeartbeatInterval int64                  `protobuf:"varint,5,opt,name=next_heartbeat_interval,json=nextHeartbeatInterval,proto3" json:"next_heartbeat_interval,omitempty"` // 下次心跳间隔（秒）
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HeartbeatResponse) GetDefenseConfig() *DefenseConfig {
	if x != nil {
		return x.DefenseConfig
	}
	return nil
}

func (x *HeartbeatResponse) GetRemainingQuota() uint64 {
	if x != nil {
		return x.RemainingQuota
	}
	return 0
}

func (x *HeartbeatResponse) GetNextHeartbeatInterval() int64 {
	if x != nil {
		return x.NextHeartbeatInterval
	}
	return 0
}

type DefenseConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DefenseLevel   uint32                 `protobuf:"varint,1,opt,name=defense_level,json=defenseLevel,proto3" json:"defense_level,omitempty"`         // 防御等级 (0-5)
	JitterMeanUs   uint32                 `protobuf:"varint,2,opt,name=jitter_mean_us,json=jitterMeanUs,proto3" json:"jitter_mean_us,omitempty"`       // Jitter 平均值（微秒）
	JitterStddevUs uint32                 `protobuf:"varint,3,opt,name=jitter_stddev_us,json=jitterStddevUs,proto3" json:"jitter_stddev_us,omitempty"` // Jitter 标准差（微秒）
	NoiseIntensity uint32                 `protobuf:"varint,4,opt,name=noise_intensity,json=noiseIntensity,proto3" json:"noise_intensity,omitempty"`   // 噪声强度 (0-100)
	PaddingRate    uint32                 `protobuf:"varint,5,opt,name=padding_rate,json=paddingRate,proto3" json:"padding_rate,omitempty"`            // 填充率 (0-100)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DefenseConfig) Reset() {
	*x = DefenseConfig{}
	mi := &file_api_proto_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefenseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefenseConfig) ProtoMessage() {}

func (x *DefenseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefenseConfig.ProtoReflect.Descriptor instead.
func (*DefenseConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *DefenseConfig) GetDefenseLevel() uint32 {
	if x != nil {
		return x.DefenseLevel
	}
	return 0
}

func (x *DefenseConfig) GetJitterMeanUs() uint32 {
	if x != nil {
		return x.JitterMeanUs
	}
	return 0
}

func (x *DefenseConfig) GetJitterStddevUs() uint32 {
	if x != nil {
		return x.JitterStddevUs
	}
	return 0
}

func (x *DefenseConfig) GetNoiseIntensity() uint32 {
	if x != nil {
		return x.NoiseIntensity
	}
	return 0
}

func (x *DefenseConfig) GetPaddingRate() uint32 {
	if x != nil {
		return x.PaddingRate
	}
	return 0
}

type TrafficReport struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	GatewayId           string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`                                  // Gateway ID
	Timestamp           int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                  // 时间戳
	BaseTrafficBytes    uint64                 `protobuf:"varint,3,opt,name=base_traffic_bytes,json=baseTrafficBytes,proto3" json:"base_traffic_bytes,omitempty"`          // 业务流量（字节）
	DefenseTrafficBytes uint64                 `protobuf:"varint,4,opt,name=defense_traffic_bytes,json=defenseTrafficBytes,proto3" json:"defense_traffic_bytes,omitempty"` // 防御流量（字节）
	CellLevel           string                 `protobuf:"bytes,5,opt,name=cell_level,json=cellLevel,proto3" json:"cell_level,omitempty"`                                  // 蜂窝等级（standard/platinum/diamond）
	Breakdown           *TrafficBreakdown      `protobuf:"bytes,6,opt,name=breakdown,proto3" json:"breakdown,omitempty"`                                                   // 流量细分
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TrafficReport) Reset() {
	*x = TrafficReport{}
	mi := &file_api_proto_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficReport) ProtoMessage() {}

func (x *TrafficReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficReport.ProtoReflect.Descriptor instead.
func (*TrafficReport) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *TrafficReport) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *TrafficReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TrafficReport) GetBaseTrafficBytes() uint64 {
	if x != nil {
		return x.BaseTrafficBytes
	}
	return 0
}

func (x *TrafficReport) GetDefenseTrafficBytes() uint64 {
	if x != nil {
		return x.DefenseTrafficBytes
	}
	return 0
}

func (x *TrafficReport) GetCellLevel() string {
	if x != nil {
		return x.CellLevel
	}
	return ""
}

func (x *TrafficReport) GetBreakdown() *TrafficBreakdown {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

type TrafficBreakdown struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NpmPaddingBytes uint64                 `protobuf:"varint,7,opt,name=npm_padding_bytes,json=npmPaddingBytes,proto3" json:"npm_padding_bytes,omitempty"` // NPM 填充流量
	VpcNoiseBytes   uint64                 `protobuf:"varint,8,opt,name=vpc_noise_bytes,json=vpcNoiseBytes,proto3" json:"vpc_noise_bytes,omitempty"`       // VPC 噪声流量
	GtunnelFecBytes uint64                 `protobuf:"varint,9,opt,name=gtunnel_fec_bytes,json=gtunnelFecBytes,proto3" json:"gtunnel_fec_bytes,omitempty"` // G-Tunnel FEC 流量
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TrafficBreakdown) Reset() {
	*x = TrafficBreakdown{}
	mi := &file_api_proto_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficBreakdown) ProtoMessage() {}

func (x *TrafficBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficBreakdown.ProtoReflect.Descriptor instead.
func (*TrafficBreakdown) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *TrafficBreakdown) GetNpmPaddingBytes() uint64 {
	if x != nil {
		return x.NpmPaddingBytes
	}
	return 0
}

func (x *TrafficBreakdown) GetVpcNoiseBytes() uint64 {
	if x != nil {
		return x.VpcNoiseBytes
	}
	return 0
}

func (x *TrafficBreakdown) GetGtunnelFecBytes() uint64 {
	if x != nil {
		return x.GtunnelFecBytes
	}
	return 0
}

type TrafficResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                        // 是否成功
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                         // 响应消息
	RemainingQuota uint64                 `protobuf:"varint,3,opt,name=remaining_quota,json=remainingQuota,proto3" json:"remaining_quota,omitempty"`    // 剩余配额
	CurrentCostUsd float32                `protobuf:"fixed32,4,opt,name=current_cost_usd,json=currentCostUsd,proto3" json:"current_cost_usd,omitempty"` // 当前费用（美元）
	QuotaWarning   bool                   `protobuf:"varint,5,opt,name=quota_warning,json=quotaWarning,proto3" json:"quota_warning,omitempty"`          // 配额告警（< 10%）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrafficResponse) Reset() {
	*x = TrafficResponse{}
	mi := &file_api_proto_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficResponse) ProtoMessage() {}

func (x *TrafficResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficResponse.ProtoReflect.Descriptor instead.
func (*TrafficResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *TrafficResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrafficResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TrafficResponse) GetRemainingQuota() uint64 {
	if x != nil {
		return x.RemainingQuota
	}
	return 0
}

func (x *TrafficResponse) GetCurrentCostUsd() float32 {
	if x != nil {
		return x.CurrentCostUsd
	}
	return 0
}

func (x *TrafficResponse) GetQuotaWarning() bool {
	if x != nil {
		return x.QuotaWarning
	}
	return false
}

type ThreatReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GatewayId      string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`                                       // Gateway ID
	Timestamp      int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                       // 时间戳（纳秒）
	ThreatType     ThreatType             `protobuf:"varint,3,opt,name=threat_type,json=threatType,proto3,enum=mirage.gateway.v1.ThreatType" json:"threat_type,omitempty"` // 威胁类型
	SourceIp       string                 `protobuf:"bytes,4,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`                                          // 源 IP
	SourcePort     uint32                 `protobuf:"varint,5,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`                                   // 源端口
	Severity       uint32                 `protobuf:"varint,6,opt,name=severity,proto3" json:"severity,omitempty"`                                                         // 严重程度 (0-10)
	PacketCount    uint32                 `protobuf:"varint,7,opt,name=packet_count,json=packetCount,proto3" json:"packet_count,omitempty"`                                // 数据包计数
	Ja4Fingerprint []byte                 `protobuf:"bytes,8,opt,name=ja4_fingerprint,json=ja4Fingerprint,proto3" json:"ja4_fingerprint,omitempty"`                        // JA4 指纹
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ThreatReport) Reset() {
	*x = ThreatReport{}
	mi := &file_api_proto_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatReport) ProtoMessage() {}

func (x *ThreatReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatReport.ProtoReflect.Descriptor instead.
func (*ThreatReport) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *ThreatReport) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *ThreatReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ThreatReport) GetThreatType() ThreatType {
	if x != nil {
		return x.ThreatType
	}
	return ThreatType_THREAT_UNKNOWN
}

func (x *ThreatReport) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *ThreatReport) GetSourcePort() uint32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *ThreatReport) GetSeverity() uint32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *ThreatReport) GetPacketCount() uint32 {
	if x != nil {
		return x.PacketCount
	}
	return 0
}

func (x *ThreatReport) GetJa4Fingerprint() []byte {
	if x != nil {
		return x.Ja4Fingerprint
	}
	return nil
}

type ThreatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                          // 是否成功
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                           // 响应消息
	Action          ThreatAction           `protobuf:"varint,3,opt,name=action,proto3,enum=mirage.gateway.v1.ThreatAction" json:"action,omitempty"`        // 建议动作
	NewDefenseLevel uint32                 `protobuf:"varint,4,opt,name=new_defense_level,json=newDefenseLevel,proto3" json:"new_defense_level,omitempty"` // 新的防御等级
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ThreatResponse) Reset() {
	*x = ThreatResponse{}
	mi := &file_api_proto_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatResponse) ProtoMessage() {}

func (x *ThreatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatResponse.ProtoReflect.Descriptor instead.
func (*ThreatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *ThreatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ThreatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ThreatResponse) GetAction() ThreatAction {
	if x != nil {
		return x.Action
	}
	return ThreatAction_ACTION_NONE
}

func (x *ThreatResponse) GetNewDefenseLevel() uint32 {
	if x != nil {
		return x.NewDefenseLevel
	}
	return 0
}

type QuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GatewayId     string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"` // Gateway ID
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 用户 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaRequest) Reset() {
	*x = QuotaRequest{}
	mi := &file_api_proto_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaRequest) ProtoMessage() {}

func (x *QuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaRequest.ProtoReflect.Descriptor instead.
func (*QuotaRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *QuotaRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *QuotaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type QuotaResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                     // 是否成功
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                      // 响应消息
	RemainingBytes uint64                 `protobuf:"varint,3,opt,name=remaining_bytes,json=remainingBytes,proto3" json:"remaining_bytes,omitempty"` // 剩余流量（字节）
	TotalBytes     uint64                 `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`             // 总配额（字节）
	ExpiresAt      int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`                // 过期时间（Unix 秒）
	AutoRenew      bool                   `protobuf:"varint,6,opt,name=auto_renew,json=autoRenew,proto3" json:"auto_renew,omitempty"`                // 自动续费
	CellQuota      *CellQuota             `protobuf:"bytes,7,opt,name=cell_quota,json=cellQuota,proto3" json:"cell_quota,omitempty"`                 // 蜂窝配额
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuotaResponse) Reset() {
	*x = QuotaResponse{}
	mi := &file_api_proto_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaResponse) ProtoMessage() {}

func (x *QuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaResponse.ProtoReflect.Descriptor instead.
func (*QuotaResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *QuotaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QuotaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QuotaResponse) GetRemainingBytes() uint64 {
	if x != nil {
		return x.RemainingBytes
	}
	return 0
}

func (x *QuotaResponse) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *QuotaResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *QuotaResponse) GetAutoRenew() bool {
	if x != nil {
		return x.AutoRenew
	}
	return false
}

func (x *QuotaResponse) GetCellQuota() *CellQuota {
	if x != nil {
		return x.CellQuota
	}
	return nil
}

type CellQuota struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CellId         string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`                           // 蜂窝 ID
	CellLevel      string                 `protobuf:"bytes,2,opt,name=cell_level,json=cellLevel,proto3" json:"cell_level,omitempty"`                  // 蜂窝等级
	AllocatedBytes uint64                 `protobuf:"varint,3,opt,name=allocated_bytes,json=allocatedBytes,proto3" json:"allocated_bytes,omitempty"`  // 分配流量
	UsedBytes      uint64                 `protobuf:"varint,4,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`                 // 已用流量
	CostMultiplier float32                `protobuf:"fixed32,5,opt,name=cost_multiplier,json=costMultiplier,proto3" json:"cost_multiplier,omitempty"` // 成本倍率
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CellQuota) Reset() {
	*x = CellQuota{}
	mi := &file_api_proto_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellQuota) ProtoMessage() {}

func (x *CellQuota) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellQuota.ProtoReflect.Descriptor instead.
func (*CellQuota) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *CellQuota) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *CellQuota) GetCellLevel() string {
	if x != nil {
		return x.CellLevel
	}
	return ""
}

func (x *CellQuota) GetAllocatedBytes() uint64 {
	if x != nil {
		return x.AllocatedBytes
	}
	return 0
}

func (x *CellQuota) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *CellQuota) GetCostMultiplier() float32 {
	if x != nil {
		return x.CostMultiplier
	}
	return 0
}

var File_api_proto_gateway_proto protoreflect.FileDescriptor

const file_api_proto_gateway_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/gateway.proto\x12\x11mirage.gateway.v1\"\x93\x02\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x120\n" +
	"\x14current_threat_level\x18\x03 \x01(\rR\x12currentThreatLevel\x128\n" +
	"\x06status\x18\x04 \x01(\v2 .mirage.gateway.v1.GatewayStatusR\x06status\x12<\n" +
	"\bresource\x18\x05 \x01(\v2 .mirage.gateway.v1.ResourceUsageR\bresource\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\xae\x01\n" +
	"\rGatewayStatus\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online\x12-\n" +
	"\x12active_connections\x18\x02 \x01(\rR\x11activeConnections\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x04R\ruptimeSeconds\x12\x17\n" +
	"\acell_id\x18\x04 \x01(\tR\x06cellId\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\"x\n" +
	"\rResourceUsage\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x02R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x04R\vmemoryBytes\x12#\n" +
	"\rbandwidth_bps\x18\x03 \x01(\x04R\fbandwidthBps\"\xf1\x01\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12G\n" +
	"\x0edefense_config\x18\x03 \x01(\v2 .mirage.gateway.v1.DefenseConfigR\rdefenseConfig\x12'\n" +
	"\x0fremaining_quota\x18\x04 \x01(\x04R\x0eremainingQuota\x126\n" +
	"\x17next_heartbeat_interval\x18\x05 \x01(\x03R\x15nextHeartbeatInterval\"\xd0\x01\n" +
	"\rDefenseConfig\x12#\n" +
	"\rdefense_level\x18\x01 \x01(\rR\fdefenseLevel\x12$\n" +
	"\x0ejitter_mean_us\x18\x02 \x01(\rR\fjitterMeanUs\x12(\n" +
	"\x10jitter_stddev_us\x18\x03 \x01(\rR\x0ejitterStddevUs\x12'\n" +
	"\x0fnoise_intensity\x18\x04 \x01(\rR\x0enoiseIntensity\x12!\n" +
	"\fpadding_rate\x18\x05 \x01(\rR\vpaddingRate\"\x90\x02\n" +
	"\rTrafficReport\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12,\n" +
	"\x12base_traffic_bytes\x18\x03 \x01(\x04R\x10baseTrafficBytes\x122\n" +
	"\x15defense_traffic_bytes\x18\x04 \x01(\x04R\x13defenseTrafficBytes\x12\x1d\n" +
	"\n" +
	"cell_level\x18\x05 \x01(\tR\tcellLevel\x12A\n" +
	"\tbreakdown\x18\x06 \x01(\v2#.mirage.gateway.v1.TrafficBreakdownR\tbreakdown\"\x92\x01\n" +
	"\x10TrafficBreakdown\x12*\n" +
	"\x11npm_padding_bytes\x18\a \x01(\x04R\x0fnpmPaddingBytes\x12&\n" +
	"\x0fvpc_noise_bytes\x18\b \x01(\x04R\rvpcNoiseBytes\x12*\n" +
	"\x11gtunnel_fec_bytes\x18\t \x01(\x04R\x0fgtunnelFecBytes\"\xbd\x01\n" +
	"\x0fTrafficResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fremaining_quota\x18\x03 \x01(\x04R\x0eremainingQuota\x12(\n" +
	"\x10current_cost_usd\x18\x04 \x01(\x02R\x0ecurrentCostUsd\x12#\n" +
	"\rquota_warning\x18\x05 \x01(\bR\fquotaWarning\"\xb1\x02\n" +
	"\fThreatReport\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12>\n" +
	"\vthreat_type\x18\x03 \x01(\x0e2\x1d.mirage.gateway.v1.ThreatTypeR\n" +
	"threatType\x12\x1b\n" +
	"\tsource_ip\x18\x04 \x01(\tR\bsourceIp\x12\x1f\n" +
	"\vsource_port\x18\x05 \x01(\rR\n" +
	"sourcePort\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\rR\bseverity\x12!\n" +
	"\fpacket_count\x18\a \x01(\rR\vpacketCount\x12'\n" +
	"\x0fja4_fingerprint\x18\b \x01(\fR\x0eja4Fingerprint\"\xa9\x01\n" +
	"\x0eThreatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x06action\x18\x03 \x01(\x0e2\x1f.mirage.gateway.v1.ThreatActionR\x06action\x12*\n" +
	"\x11new_defense_level\x18\x04 \x01(\rR\x0fnewDefenseLevel\"F\n" +
	"\fQuotaRequest\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x88\x02\n" +
	"\rQuotaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fremaining_bytes\x18\x03 \x01(\x04R\x0eremainingBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\x12\x1d\n" +
	"\n" +
	"auto_renew\x18\x06 \x01(\bR\tautoRenew\x12;\n" +
	"\n" +
	"cell_quota\x18\a \x01(\v2\x1c.mirage.gateway.v1.CellQuotaR\tcellQuota\"\xb4\x01\n" +
	"\tCellQuota\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\x12\x1d\n" +
	"\n" +
	"cell_level\x18\x02 \x01(\tR\tcellLevel\x12'\n" +
	"\x0fallocated_bytes\x18\x03 \x01(\x04R\x0eallocatedBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x04 \x01(\x04R\tusedBytes\x12'\n" +
	"\x0fcost_multiplier\x18\x05 \x01(\x02R\x0ecostMultiplier*\xb5\x01\n" +
	"\n" +
	"ThreatType\x12\x12\n" +
	"\x0eTHREAT_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15THREAT_ACTIVE_PROBING\x10\x01\x12\x13\n" +
	"\x0fTHREAT_JA4_SCAN\x10\x02\x12\x14\n" +
	"\x10THREAT_SNI_PROBE\x10\x03\x12\x19\n" +
	"\x15THREAT_DPI_INSPECTION\x10\x04\x12\x18\n" +
	"\x14THREAT_TIMING_ATTACK\x10\x05\x12\x18\n" +
	"\x14THREAT_REPLAY_ATTACK\x10\x06*\x88\x01\n" +
	"\fThreatAction\x12\x0f\n" +
	"\vACTION_NONE\x10\x00\x12\x1b\n" +
	"\x17ACTION_INCREASE_DEFENSE\x10\x01\x12\x13\n" +
	"\x0fACTION_BLOCK_IP\x10\x02\x12\x16\n" +
	"\x12ACTION_SWITCH_CELL\x10\x03\x12\x1d\n" +
	"\x19ACTION_EMERGENCY_SHUTDOWN\x10\x042\xe6\x02\n" +
	"\x0eGatewayService\x12Z\n" +
	"\rSyncHeartbeat\x12#.mirage.gateway.v1.HeartbeatRequest\x1a$.mirage.gateway.v1.HeartbeatResponse\x12U\n" +
	"\rReportTraffic\x12 .mirage.gateway.v1.TrafficReport\x1a\".mirage.gateway.v1.TrafficResponse\x12R\n" +
	"\fReportThreat\x12\x1f.mirage.gateway.v1.ThreatReport\x1a!.mirage.gateway.v1.ThreatResponse\x12M\n" +
	"\bGetQuota\x12\x1f.mirage.gateway.v1.QuotaRequest\x1a .mirage.gateway.v1.QuotaResponseB\x18Z\x16mirage-os/api/proto;pbb\x06proto3"

var (
	file_api_proto_gateway_proto_rawDescOnce sync.Once
	file_api_proto_gateway_proto_rawDescData []byte
)

func file_api_proto_gateway_proto_rawDescGZIP() []byte {
	file_api_proto_gateway_proto_rawDescOnce.Do(func() {
		file_api_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_gateway_proto_rawDesc), len(file_api_proto_gateway_proto_rawDesc)))
	})
	return file_api_proto_gateway_proto_rawDescData
}

var file_api_proto_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_gateway_proto_goTypes = []any{
	(ThreatType)(0),           // 0: mirage.gateway.v1.ThreatType
	(ThreatAction)(0),         // 1: mirage.gateway.v1.ThreatAction
	(*HeartbeatRequest)(nil),  // 2: mirage.gateway.v1.HeartbeatRequest
	(*GatewayStatus)(nil),     // 3: mirage.gateway.v1.GatewayStatus
	(*ResourceUsage)(nil),     // 4: mirage.gateway.v1.ResourceUsage
	(*HeartbeatResponse)(nil), // 5: mirage.gateway.v1.HeartbeatResponse
	(*DefenseConfig)(nil),     // 6: mirage.gateway.v1.DefenseConfig
	(*TrafficReport)(nil),     // 7: mirage.gateway.v1.TrafficReport
	(*TrafficBreakdown)(nil),  // 8: mirage.gateway.v1.TrafficBreakdown
	(*TrafficResponse)(nil),   // 9: mirage.gateway.v1.TrafficResponse
	(*ThreatReport)(nil),      // 10: mirage.gateway.v1.ThreatReport
	(*ThreatResponse)(nil),    // 11: mirage.gateway.v1.ThreatResponse
	(*QuotaRequest)(nil),      // 12: mirage.gateway.v1.QuotaRequest
	(*QuotaResponse)(nil),     // 13: mirage.gateway.v1.QuotaResponse
	(*CellQuota)(nil),         // 14: mirage.gateway.v1.CellQuota
}
var file_api_proto_gateway_proto_depIdxs = []int32{
	3,  // 0: mirage.gateway.v1.HeartbeatRequest.status:type_name -> mirage.gateway.v1.GatewayStatus
	4,  // 1: mirage.gateway.v1.HeartbeatRequest.resource:type_name -> mirage.gateway.v1.ResourceUsage
	6,  // 2: mirage.gateway.v1.HeartbeatResponse.defense_config:type_name -> mirage.gateway.v1.DefenseConfig
	8,  // 3: mirage.gateway.v1.TrafficReport.breakdown:type_name -> mirage.gateway.v1.TrafficBreakdown
	0,  // 4: mirage.gateway.v1.ThreatReport.threat_type:type_name -> mirage.gateway.v1.ThreatType
	1,  // 5: mirage.gateway.v1.ThreatResponse.action:type_name -> mirage.gateway.v1.ThreatAction
	14, // 6: mirage.gateway.v1.QuotaResponse.cell_quota:type_name -> mirage.gateway.v1.CellQuota
	2,  // 7: mirage.gateway.v1.GatewayService.SyncHeartbeat:input_type -> mirage.gateway.v1.HeartbeatRequest
	7,  // 8: mirage.gateway.v1.GatewayService.ReportTraffic:input_type -> mirage.gateway.v1.TrafficReport
	10, // 9: mirage.gateway.v1.GatewayService.ReportThreat:input_type -> mirage.gateway.v1.ThreatReport
	12, // 10: mirage.gateway.v1.GatewayService.GetQuota:input_type -> mirage.gateway.v1.QuotaRequest
	5,  // 11: mirage.gateway.v1.GatewayService.SyncHeartbeat:output_type -> mirage.gateway.v1.HeartbeatResponse
	9,  // 12: mirage.gateway.v1.GatewayService.ReportTraffic:output_type -> mirage.gateway.v1.TrafficResponse
	11, // 13: mirage.gateway.v1.GatewayService.ReportThreat:output_type -> mirage.gateway.v1.ThreatResponse
	13, // 14: mirage.gateway.v1.GatewayService.GetQuota:output_type -> mirage.gateway.v1.QuotaResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_gateway_proto_init() }
func file_api_proto_gateway_proto_init() {
	if File_api_proto_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_gateway_proto_rawDesc), len(file_api_proto_gateway_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_gateway_proto_goTypes,
		DependencyIndexes: file_api_proto_gateway_proto_depIdxs,
		EnumInfos:         file_api_proto_gateway_proto_enumTypes,
		MessageInfos:      file_api_proto_gateway_proto_msgTypes,
	}.Build()
	File_api_proto_gateway_proto = out.File
	file_api_proto_gateway_proto_goTypes = nil
	file_api_proto_gateway_proto_depIdxs = nil
}
